<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Category;
use Illuminate\Support\Facades\DB;

// Production data from server output
$prodData = [
    ["name_en" => "Family Health Worker Area", "slug" => "location-1-1-5-1-1-1-1-1"],
    ["name_en" => "Reserved forest", "slug" => "location-1-1-6-2-2"],
    ["name_en" => "Forest administrative boundaries", "slug" => "location-1-1-6"],
    ["name_en" => "DIG Division", "slug" => "location-1-1-2-1-1-1"],
    ["name_en" => "Police boundaries", "slug" => "location-1-1-2"],
    ["name_en" => "Health Province", "slug" => "location-1-1-5-1"],
    ["name_en" => "Forest fields", "slug" => "location-1-1-6-1-1-1-1-1"],
    ["name_en" => "Health District", "slug" => "location-1-1-5-1-1"],
    ["name_en" => "Police Division (Police Station)", "slug" => "location-1-1-2-1-1-1-1-1"],
    ["name_en" => "Public Health Inspectorate Area", "slug" => "location-1-1-5-1-1-1-1"],
    ["name_en" => "Health Administration Boundaries", "slug" => "location-1-1-5"],
    ["name_en" => "Forest Range", "slug" => "location-1-1-6-1-1-1"],
    ["name_en" => "Forest Division", "slug" => "location-1-1-6-1-1"],
    ["name_en" => "UNESCO Heritage Forest", "slug" => "location-1-1-6-2-4"],
    ["name_en" => "The forest beet", "slug" => "location-1-1-6-1-1-1-1"],
    ["name_en" => "World Heritage Forest", "slug" => "location-1-1-6-2-5"],
    ["name_en" => "Provincial boundaries", "slug" => "location-1-1-1-1"],
    ["name_en" => "District boundaries", "slug" => "location-1-1-1-1-1"],
    ["name_en" => "Countryside forest", "slug" => "location-1-1-6-2-3"],
    ["name_en" => "Preserved forest", "slug" => "location-1-1-6-2-1"],
    ["name_en" => "Forest boundary zone", "slug" => "location-1-1-6-1"],
    ["name_en" => "Local government limits", "slug" => "location-1-1-3"],
    ["name_en" => "Grama Niladhari Divisional Boundaries", "slug" => "location-1-1-1-1-1-1-1"],
    ["name_en" => "Wildlife management Boundaries", "slug" => "location-1-1-7"],
    ["name_en" => "Village boundaries", "slug" => "location-1-1-1-1-1-1-1-1"],
    ["name_en" => "Pradeshiya Sabha Boundaries", "slug" => "location-1-1-3-1"],
    ["name_en" => "C1: Northern Wet lowlands", "slug" => "location-1-1-8-1-4"],
    ["name_en" => "Riverine Dry Forest", "slug" => "location-1-1-8-2-8"],
    ["name_en" => "Strict nature reserve", "slug" => "location-1-1-9-2-3"],
    ["name_en" => "National protected areas", "slug" => "location-1-1-9-2"],
    ["name_en" => "Wildlife forests", "slug" => "location-1-1-9"],
    ["name_en" => "Flowering plant zones", "slug" => "location-1-1-8-1"],
    ["name_en" => "Elephant Pass", "slug" => "location-1-1-9-4"],
    ["name_en" => "Wildlife Range", "slug" => "location-1-1-7-1-1"],
    ["name_en" => "Wildlife Beat", "slug" => "location-1-1-7-1-1-1"],
    ["name_en" => "Sanctuaries", "slug" => "location-1-1-9-2-2"],
    ["name_en" => "Marine Reserves", "slug" => "location-1-1-9-3"],
    ["name_en" => "Nature reserve", "slug" => "location-1-1-9-2-1"],
    ["name_en" => "Limestone rock complex", "slug" => "location-1-1-10-4"],
    ["name_en" => "DL1b Agro-ecological Zone", "slug" => "location-1-1-11-1-2"],
    ["name_en" => "DL1d Agro-ecological Zone", "slug" => "location-1-1-11-1-4"],
    ["name_en" => "DL1a Agro-ecological Zone", "slug" => "location-1-1-11-1-1"],
    ["name_en" => "DL1e Agro-ecological Zone", "slug" => "location-1-1-11-1-5"],
    ["name_en" => "DL1c Agro-ecological Zone", "slug" => "location-1-1-11-1-3"],
    ["name_en" => "Dry zone", "slug" => "location-1-1-11-1"],
    ["name_en" => "DL1f Agro-ecological Zone", "slug" => "location-1-1-11-1-6"],
    ["name_en" => "DL2a Agro-ecological Zone", "slug" => "location-1-1-11-1-7"],
    ["name_en" => "DL2b Agro-ecological Zone", "slug" => "location-1-1-11-1-8"],
    ["name_en" => "DL3 Agro-Ecological Zone", "slug" => "location-1-1-11-1-9"],
    ["name_en" => "DL4 Agro-Ecological Zone", "slug" => "location-1-1-11-1-10"],
    ["name_en" => "DL5 Agro-Ecological Zone", "slug" => "location-1-1-11-1-11"],
    ["name_en" => "IL2 Agro-Ecological Zone", "slug" => "location-1-1-11-2-4"],
    ["name_en" => "IL3 Agro-Ecological Zone", "slug" => "location-1-1-11-2-5"],
    ["name_en" => "IM2b Agro-ecological Zone", "slug" => "location-1-1-11-2-10"],
    ["name_en" => "IM3a Agro-ecological Zone", "slug" => "location-1-1-11-2-11"],
    ["name_en" => "IM3b Agro-ecological Zone", "slug" => "location-1-1-11-2-12"],
    ["name_en" => "IM3c Agro-ecological Zone", "slug" => "location-1-1-11-2-13"],
    ["name_en" => "Highland rock complex", "slug" => "location-1-1-10-1"],
    ["name_en" => "Vanni Rock Complex", "slug" => "location-1-1-10-2"],
    ["name_en" => "Vijayan Rock Complex", "slug" => "location-1-1-10-3"],
    ["name_en" => "Kadugannawa Rock Complex", "slug" => "location-1-1-10-5"],
    ["name_en" => "IL1a Agro-ecological Zone", "slug" => "location-1-1-11-2-1"],
    ["name_en" => "IL1b Agro-ecological Zone", "slug" => "location-1-1-11-2-2"],
    ["name_en" => "IL1c Agro-Ecological Zone", "slug" => "location-1-1-11-2-3"],
    ["name_en" => "IM1a Agro-ecological Zone", "slug" => "location-1-1-11-2-6"],
    ["name_en" => "IM1c Agro-ecological Zone", "slug" => "location-1-1-11-2-8"],
    ["name_en" => "IM2a Agro-ecological Zone", "slug" => "location-1-1-11-2-9"],
    ["name_en" => "WL2a Agro-ecological Zone", "slug" => "location-1-1-11-3-3"],
    ["name_en" => "Wet zone", "slug" => "location-1-1-11-3"],
    ["name_en" => "WL2b Agro-ecological Zone", "slug" => "location-1-1-11-3-4"],
    ["name_en" => "WL3 Agro-Ecological Zone", "slug" => "location-1-1-11-3-5"],
    ["name_en" => "WM1a Agro-ecological Zone", "slug" => "location-1-1-11-3-6"],
    ["name_en" => "WM1b Agro-ecological Zone", "slug" => "location-1-1-11-3-7"],
    ["name_en" => "WM3a Agro-ecological Zone", "slug" => "location-1-1-11-3-10"],
    ["name_en" => "WM3b Agro-ecological Zone", "slug" => "location-1-1-11-3-11"],
    ["name_en" => "WU1 Agro-Ecological Zone", "slug" => "location-1-1-11-3-12"],
    ["name_en" => "WU2a Agro-ecological Zone", "slug" => "location-1-1-11-3-13"],
    ["name_en" => "WU2b Agro-ecological Zone", "slug" => "location-1-1-11-3-14"],
    ["name_en" => "Bulutota-Rakwana", "slug" => "location-1-1-12-1-2"],
    ["name_en" => "Coastal Plain", "slug" => "location-1-1-12-3"],
    ["name_en" => "IU3bAgro-ecological zone", "slug" => "location-1-1-11-2-17"],
    ["name_en" => "IU1 Agro-Ecological Zone", "slug" => "location-1-1-11-2-14"],
    ["name_en" => "IU2 Agro-Ecological Zone", "slug" => "location-1-1-11-2-15"],
    ["name_en" => "IU3e Agro-Ecological Zone", "slug" => "location-1-1-11-2-20"],
    ["name_en" => "IU3a Agro-ecological Zone", "slug" => "location-1-1-11-2-16"],
    ["name_en" => "IU3c Agro-ecological Zone", "slug" => "location-1-1-11-2-18"],
    ["name_en" => "IU3d Agro-Ecological Zone", "slug" => "location-1-1-11-2-19"],
    ["name_en" => "WL1a Agro-ecological Zone", "slug" => "location-1-1-11-3-1"],
    ["name_en" => "WL1b Agro-ecological Zone", "slug" => "location-1-1-11-3-2"],
    ["name_en" => "WM2a Agro-ecological Zone", "slug" => "location-1-1-11-3-8"],
    ["name_en" => "WU3 Agro-Ecological Zone", "slug" => "location-1-1-11-3-15"],
    ["name_en" => "Lowland wet zone", "slug" => "location-1-1-13-1"],
    ["name_en" => "Intermediate zone", "slug" => "location-1-1-13-3"],
    ["name_en" => "Mountainous region", "slug" => "location-1-1-12-1"],
    ["name_en" => "Galoya", "slug" => "location-1-1-12-1-3"],
    ["name_en" => "Mountainous region", "slug" => "location-1-1-13-2"],
    ["name_en" => "Agricultural Services Area", "slug" => "location-1-1-11-4"],
    ["name_en" => "Middle", "slug" => "location-1-1-12-1-1"],
    ["name_en" => "Inland Plain", "slug" => "location-1-1-12-2"],
    ["name_en" => "Community", "slug" => "location-1-1-17-1-1-1-1-1"],
    ["name_en" => "Archaeological Zone", "slug" => "location-1-1-19-1-1"],
    ["name_en" => "Education Division", "slug" => "location-1-1-16-1-1-1"],
    ["name_en" => "School", "slug" => "location-1-1-16-1-1-1-1"],
    ["name_en" => "Pirivena", "slug" => "location-1-1-16-1-1-1-2"],
    ["name_en" => "Disaster zones", "slug" => "location-1-1-17"],
    ["name_en" => "National", "slug" => "location-1-1-17-1"],
    ["name_en" => "District", "slug" => "location-1-1-17-1-1-1"],
    ["name_en" => "Telecommunications", "slug" => "location-1-1-18"],
    ["name_en" => "Telecom", "slug" => "location-1-1-18-2"],
    ["name_en" => "Telecom Regional Area", "slug" => "location-1-1-18-2-1-1-1"],
    ["name_en" => "Telecom Local Exchange Area", "slug" => "location-1-1-18-2-1-1-1-1"],
    ["name_en" => "Archaeological District Division", "slug" => "location-1-1-19-1"],
    ["name_en" => "Archaeological site", "slug" => "location-1-1-19-1-1-1"],
    ["name_en" => "Telecommunications towers", "slug" => "location-1-1-18-1"],
    ["name_en" => "Dry zone", "slug" => "location-1-1-13-4"],
    ["name_en" => "Wet zone", "slug" => "location-1-1-14-1"],
    ["name_en" => "Semi-arid zone", "slug" => "location-1-1-13-5"],
    ["name_en" => "Education Zone", "slug" => "location-1-1-16-1-1"],
    ["name_en" => "Intermediate zone", "slug" => "location-1-1-14-2"],
    ["name_en" => "Weather station", "slug" => "location-1-1-13-6"],
    ["name_en" => "Rain gauge", "slug" => "location-1-1-13-7"],
    ["name_en" => "Distribution Region", "slug" => "location-1-1-15-1"],
    ["name_en" => "Electricity Province", "slug" => "location-1-1-15-1-1"],
    ["name_en" => "Education Province", "slug" => "location-1-1-16-1"],
    ["name_en" => "Telecom Province DGM", "slug" => "location-1-1-18-2-1-1"],
    ["name_en" => "Semi-arid zone", "slug" => "location-1-1-14-4"],
    ["name_en" => "District", "slug" => "location-1-1-18-1-1-1"],
    ["name_en" => "Electrical area", "slug" => "location-1-1-15-1-1-1"],
    ["name_en" => "Electrical grid", "slug" => "location-1-1-15-1-1-1-1"],
    ["name_en" => "Power plant", "slug" => "location-1-1-15-1-1-1-2"],
    ["name_en" => "Provinces", "slug" => "location-1-1-17-1-1"],
    ["name_en" => "Divisions", "slug" => "location-1-1-17-1-1-1-1"],
    ["name_en" => "Provinces", "slug" => "location-1-1-18-1-1"],
    ["name_en" => "Divisions and communities", "slug" => "location-1-1-18-1-1-1-1"],
    ["name_en" => "Telecom Regions (Provinces)", "slug" => "location-1-1-18-2-1"],
    ["name_en" => "School Education", "slug" => "location-1-1-16"],
    ["name_en" => "Raigama (Kotte era)", "slug" => "location-1-1-20-5-1"],
    ["name_en" => "Kotte (Kotte era)", "slug" => "location-1-1-20-5-2"],
    ["name_en" => "Senkadagala (Kotte era)", "slug" => "location-1-1-20-5-4"],
    ["name_en" => "Vanni (Kotte era)", "slug" => "location-1-1-20-5-5"],
    ["name_en" => "Kandy era", "slug" => "location-1-1-20-6"],
    ["name_en" => "Portuguese era", "slug" => "location-1-1-20-7"],
    ["name_en" => "Coastal (Portuguese era)", "slug" => "location-1-1-20-7-1"],
    ["name_en" => "Dutch era", "slug" => "location-1-1-20-8"],
    ["name_en" => "Jaffna (Dutch era)", "slug" => "location-1-1-20-8-1"],
    ["name_en" => "Colombo (Dutch era)", "slug" => "location-1-1-20-8-2"],
    ["name_en" => "Galle (Dutch era)", "slug" => "location-1-1-20-8-3"],
    ["name_en" => "Ruhuna (Anuradhapura period)", "slug" => "location-1-1-20-2-1"],
    ["name_en" => "Anuradhapura era", "slug" => "location-1-1-20-2"],
    ["name_en" => "Polonnaruwa era", "slug" => "location-1-1-20-3"],
    ["name_en" => "Maya (Anuradhapura period)", "slug" => "location-1-1-20-2-3"],
    ["name_en" => "Malaya (Anuradhapura period)", "slug" => "location-1-1-20-2-4"],
    ["name_en" => "Uttara Desha (Polonnaru Era)", "slug" => "location-1-1-20-3-1"],
    ["name_en" => "Rohana (Polonnaru era)", "slug" => "location-1-1-20-3-3"],
    ["name_en" => "Malaya (Polonnaru period)", "slug" => "location-1-1-20-3-5"],
    ["name_en" => "Post-Polonnaru era", "slug" => "location-1-1-20-4"],
    ["name_en" => "Seethawaka (Kotte era)", "slug" => "location-1-1-20-5-3"],
    ["name_en" => "Kandy (Portuguese period)", "slug" => "location-1-1-20-7-2"],
    ["name_en" => "Before the Anuradhapura era", "slug" => "location-1-1-20-1"],
    ["name_en" => "Located (Anuradhapura period)", "slug" => "location-1-1-20-2-2"],
    ["name_en" => "Southern Land (Maya) (Polonnaru Era)", "slug" => "location-1-1-20-3-2"],
    ["name_en" => "The Kotte era", "slug" => "location-1-1-20-5"],
    ["name_en" => "Kingdom of Kandy", "slug" => "location-1-1-20-8-4"],
    ["name_en" => "English era", "slug" => "location-1-1-20-9"],
    ["name_en" => "North (English era)", "slug" => "location-1-1-20-9-1"],
    ["name_en" => "East (English era)", "slug" => "location-1-1-20-9-2"],
    ["name_en" => "Western (English era)", "slug" => "location-1-1-20-9-3"],
    ["name_en" => "South (English era)", "slug" => "location-1-1-20-9-4"],
    ["name_en" => "Agricultural District Region", "slug" => "location-1-1-22-1"],
    ["name_en" => "Sub Post Office", "slug" => "location-1-1-21-1-1-1-1"],
    ["name_en" => "Weather stations", "slug" => "location-1-1-23"],
    ["name_en" => "Postal province", "slug" => "location-1-1-21-1"],
    ["name_en" => "Postal District", "slug" => "location-1-1-21-1-1"],
    ["name_en" => "Middle (English era)", "slug" => "location-1-1-20-9-5"],
    ["name_en" => "Head Post Office", "slug" => "location-1-1-21-1-1-1"],
    ["name_en" => "Agricultural Services Area", "slug" => "location-1-1-22-1-1"],
    ["name_en" => "Basic administrative divisions", "slug" => "location-1-1-1"],
    ["name_en" => "Medical Officer of Health Area of ​​Jurisdiction", "slug" => "location-1-1-5-1-1-1"],
    ["name_en" => "Natural zone boundaries Nature", "slug" => "location-1-1-8"],
    ["name_en" => "Climate zones", "slug" => "location-1-1-13"],
    ["name_en" => "Rainfall zones", "slug" => "location-1-1-14"],
    ["name_en" => "Electricity distribution", "slug" => "location-1-1-15"],
    ["name_en" => "Archaeological boundaries", "slug" => "location-1-1-19"],
    ["name_en" => "Postal Boundaries", "slug" => "location-1-1-21"],
    ["name_en" => "Agro-ecological zones", "slug" => "location-1-1-11"],
    ["name_en" => "Topographical zones", "slug" => "location-1-1-12"],
    ["name_en" => "Rocky regions", "slug" => "location-1-1-10"],
    ["name_en" => "Old state boundaries", "slug" => "location-1-1-20"],
    ["name_en" => "SDIG Division", "slug" => "location-1-1-2-1-1"],
    ["name_en" => "G: Central Mountains Ramboda - Nuwara Eliya", "slug" => "location-1-1-8-1-10"],
    ["name_en" => "Open & Sparse Forest", "slug" => "location-1-1-8-2-6"],
    ["name_en" => "Dry Monsoon Forest", "slug" => "location-1-1-8-2-2"],
    ["name_en" => "Moist Monsoon Forest", "slug" => "location-1-1-8-2-3"],
    ["name_en" => "Assistant Director of Wildlife Area of ​​Jurisdiction", "slug" => "location-1-1-7-1"],
    ["name_en" => "Submontane Forest", "slug" => "location-1-1-8-2-5"],
    ["name_en" => "Divisional Secretariat Division Boundaries", "slug" => "location-1-1-1-1-1-1"],
    ["name_en" => "Municipal Council Area", "slug" => "location-1-1-3-3"],
    ["name_en" => "D: Foothills of Adam's Peak North of Ratnapura - Ambagamuwa", "slug" => "location-1-1-8-1-7"],
    ["name_en" => "Forest zones", "slug" => "location-1-1-8-2"],
    ["name_en" => "Urban Council Area", "slug" => "location-1-1-3-2"],
    ["name_en" => "E: Kandy - upper Mahaweli", "slug" => "location-1-1-8-1-8"],
    ["name_en" => "National parks", "slug" => "location-1-1-9-1"],
    ["name_en" => "Intermediate zone", "slug" => "location-1-1-11-2"],
    ["name_en" => "B1: Northern Intermediate lowlands", "slug" => "location-1-1-8-1-2"],
    ["name_en" => "C2: South of Ratnapura - Northern Sinharaja", "slug" => "location-1-1-8-1-5"],
    ["name_en" => "C3: Southern Sinharaja Hiniduma-Kanneliya", "slug" => "location-1-1-8-1-6"],
    ["name_en" => "IM1b Agro-ecological Zone", "slug" => "location-1-1-11-2-7"],
    ["name_en" => "WM2b Agro-ecological Zone", "slug" => "location-1-1-11-3-9"],
    ["name_en" => "Agricultural Administrative Boundary", "slug" => "location-1-1-22"],
    ["name_en" => "Mangrove", "slug" => "location-1-1-8-2-7"],
    ["name_en" => "H: Adam's Peak", "slug" => "location-1-1-8-1-11"],
    ["name_en" => "I: Horton Plains", "slug" => "location-1-1-8-1-12"],
    ["name_en" => "Marsh", "slug" => "location-1-1-8-2-12"],
    ["name_en" => "Shrub", "slug" => "location-1-1-8-2-10"],
    ["name_en" => "Dry zone", "slug" => "location-1-1-14-3"],
    ["name_en" => "Jaffna (Kotte era)", "slug" => "location-1-1-20-5-6"],
    ["name_en" => "F: Knuckles", "slug" => "location-1-1-8-1-9"],
    ["name_en" => "Lowland Rain Forest", "slug" => "location-1-1-8-2-1"],
    ["name_en" => "Montane Forest", "slug" => "location-1-1-8-2-4"],
    ["name_en" => "A: Dry zone", "slug" => "location-1-1-8-1-1"],
    ["name_en" => "B2: Eastern Intermediate lowlands", "slug" => "location-1-1-8-1-3"],
    ["name_en" => "Savannah", "slug" => "location-1-1-8-2-9"],
    ["name_en" => "Grassland", "slug" => "location-1-1-8-2-11"],
    ["name_en" => "Classification of forests according to laws", "slug" => "location-1-1-6-2"],
];

// Also add entries that have slightly different names locally vs prod
// These are manual overrides for known name mismatches
$manualMappings = [
    // Local name => prod slug
    "Provincial Boundaries"                    => "location-1-1-1-1",
    "District Boundaries"                      => "location-1-1-1-1-1",
    "Divisional Secretariat Boundaries"        => "location-1-1-1-1-1-1",
    "Grama Niladhari Division Boundaries"      => "location-1-1-1-1-1-1-1",
    "Village Boundaries"                       => "location-1-1-1-1-1-1-1-1",
    "Police Boundaries"                        => "location-1-1-2",
    "Local Government Boundaries"              => "location-1-1-3",
    "Health Administrative Boundaries"         => "location-1-1-5",
    "Forest Administrative Boundaries"         => "location-1-1-6",
    "Wildlife Administrative Boundaries"       => "location-1-1-7",
    "Natural Zone Boundaries"                  => "location-1-1-8",
    "Forest Boundary Region"                   => "location-1-1-6-1",
    "Basic Administrative Divisions"           => "location-1-1-1",
    "Archaeological Boundaries"                => "location-1-1-19",
    "Old State Boundaries"                     => "location-1-1-20",
    "Agro-ecological Zones"                    => "location-1-1-11",
    "Topographic Zones"                        => "location-1-1-12",
    "Rocky Regions"                            => "location-1-1-10",
    "Disaster Zones"                           => "location-1-1-17",
    "Climate Zones"                            => "location-1-1-13",
    "Rainfall Zones"                           => "location-1-1-14",
    "Electricity Distribution"                 => "location-1-1-15",
    "Education"                                => "location-1-1-16",
    "Telecommunications"                       => "location-1-1-18",
    "Agrarian Service Area"                    => "location-1-1-11-4",
    "Agro-ecological Zone"                     => "location-1-1-11",  // parent
    "DL3 Agro-ecological Zone"                 => "location-1-1-11-1-9",
    "DL4 Agro-ecological Zone"                 => "location-1-1-11-1-10",
    "DL5 Agro-ecological Zone"                 => "location-1-1-11-1-11",
    "IL2 Agro-ecological Zone"                 => "location-1-1-11-2-4",
    "IL3 Agro-ecological Zone"                 => "location-1-1-11-2-5",
    "IL1c Agro-ecological Zone"                => "location-1-1-11-2-3",
    "IU1 Agro-ecological Zone"                 => "location-1-1-11-2-14",
    "IU2 Agro-ecological Zone"                 => "location-1-1-11-2-15",
    "IU3a Agro-ecological Zone"                => "location-1-1-11-2-16",
    "IU3b Agro-ecological Zone"                => "location-1-1-11-2-17",
    "IU3c Agro-ecological Zone"                => "location-1-1-11-2-18",
    "IU3d Agro-ecological Zone"                => "location-1-1-11-2-19",
    "IU3e Agro-ecological Zone"                => "location-1-1-11-2-20",
    "WL3 Agro-ecological Zone"                 => "location-1-1-11-3-5",
    "WU1 Agro-ecological Zone"                 => "location-1-1-11-3-12",
    "WU3 Agro-ecological Zone"                 => "location-1-1-11-3-15",
    "WM3a Agro-ecological Zone"                => "location-1-1-11-3-10",
    "WM3b Agro-ecological Zone"                => "location-1-1-11-3-11",
    "Telecommunications Towers"               => "location-1-1-18-1",
    "Telecom Province (DGM)"                   => "location-1-1-18-2-1-1",
    "Region Telecom Zone (Province)"           => "location-1-1-18-2-1",
    "Divisional & Community"                   => "location-1-1-18-1-1-1-1",
    "Divisional Secretariat Division Boundaries" => "location-1-1-1-1-1-1",
    "Grama Niladhari Division Boundaries"      => "location-1-1-1-1-1-1-1",
    "Forest Administrative Boundaries"         => "location-1-1-6",
    "Forest Boundary Region"                   => "location-1-1-6-1",
    "Preserved Forest"                         => "location-1-1-6-2-1",
    "Countryside Forest"                       => "location-1-1-6-2-3",
    "UNESCO Heritage Forest"                   => "location-1-1-6-2-4",
    "World Heritage Forest"                    => "location-1-1-6-2-5",
    "Reserved Forest"                          => "location-1-1-6-2-2",
    "Gal Oya"                                  => "location-1-1-12-1-3",
    "Central"                                  => "location-1-1-12-1-1",
    "Mountain Region"                          => "location-1-1-12-1",
    "Interior Plain"                           => "location-1-1-12-2",
    "Lowland Wet Zone"                         => "location-1-1-13-1",
    "Mountain Zone"                            => "location-1-1-12-1",
    "Intermediate Zone"                        => "location-1-1-13-3",
    "Dry Zone"                                 => "location-1-1-13-4",
    "Semi-arid Zone"                           => "location-1-1-13-5",
    "Weather Station"                          => "location-1-1-13-6",
    "Rain Gauge"                               => "location-1-1-13-7",
    "Wet Zone"                                 => "location-1-1-14-1",
    "Sanctuaries"                              => "location-1-1-9-2-2",
    "Nature Reserve"                           => "location-1-1-9-2-1",
    "National Parks"                           => "location-1-1-9-1",
    "National Protected Areas"                 => "location-1-1-9-2",
    "Marine Reserves"                          => "location-1-1-9-3",
    "Wildlife Forests"                         => "location-1-1-9",
    "Pradeshiya Sabha"                         => "location-1-1-3-1",
    "Municipal Council"                        => "location-1-1-3-3",
    "Urban Council"                            => "location-1-1-3-2",
    "Distribution Region"                      => "location-1-1-15-1",
    "Electricity Province"                     => "location-1-1-15-1-1",
    "Electricity Area"                         => "location-1-1-15-1-1-1",
    "Electricity Grid"                         => "location-1-1-15-1-1-1-1",
    "Power Station"                            => "location-1-1-15-1-1-1-2",
    "Education Province"                       => "location-1-1-16-1",
    "Education Zone"                           => "location-1-1-16-1-1",
    "Education Division"                       => "location-1-1-16-1-1-1",
    "School"                                   => "location-1-1-16-1-1-1-1",
    "Pirivena"                                 => "location-1-1-16-1-1-1-2",
    "Disaster Zones"                           => "location-1-1-17",
    "Archaeological District Division"         => "location-1-1-19-1",
    "Archaeological Zone"                      => "location-1-1-19-1-1",
    "Archaeological Site"                      => "location-1-1-19-1-1-1",
    "Pre-Anuradhapura Era"                     => "location-1-1-20-1",
    "Anuradhapura Era"                         => "location-1-1-20-2",
    "Ruhuna (Anuradhapura Era)"                => "location-1-1-20-2-1",
    "Pihiti (Anuradhapura Era)"                => "location-1-1-20-2-2",
    "Maya (Anuradhapura Era)"                  => "location-1-1-20-2-3",
    "Malaya (Anuradhapura Era)"                => "location-1-1-20-2-4",
    "Polonnaruwa Era"                          => "location-1-1-20-3",
    "Uttara Desa (Polonnaruwa Era)"            => "location-1-1-20-3-1",
    "Dakkhina Desa (Maya) (Polonnaruwa Era)"   => "location-1-1-20-3-2",
    "Rohana (Polonnaruwa Era)"                 => "location-1-1-20-3-3",
    "Malaya (Polonnaruwa Era)"                 => "location-1-1-20-3-5",
    "Post-Polonnaruwa Era"                     => "location-1-1-20-4",
    "Kotte Era"                                => "location-1-1-20-5",
    "Raigama (Kotte Era)"                      => "location-1-1-20-5-1",
    "Kotte (Kotte Era)"                        => "location-1-1-20-5-2",
    "Sitawaka (Kotte Era)"                     => "location-1-1-20-5-3",
    "Senkadagala (Kotte Era)"                  => "location-1-1-20-5-4",
    "Vanni (Kotte Era)"                        => "location-1-1-20-5-5",
    "Jaffna (Kotte Era)"                       => "location-1-1-20-5-6",
    "Kandy Era"                                => "location-1-1-20-6",
    "Portuguese Era"                           => "location-1-1-20-7",
    "Coastal (Portuguese Era)"                 => "location-1-1-20-7-1",
    "Kandy (Portuguese Era)"                   => "location-1-1-20-7-2",
    "Dutch Era"                                => "location-1-1-20-8",
    "Jaffna (Dutch Era)"                       => "location-1-1-20-8-1",
    "Colombo (Dutch Era)"                      => "location-1-1-20-8-2",
    "Galle (Dutch Era)"                        => "location-1-1-20-8-3",
    "Kandy Kingdom (Dutch Era)"                => "location-1-1-20-8-4",
    "British Era"                              => "location-1-1-20-9",
    "North (British Era)"                      => "location-1-1-20-9-1",
    "East (British Era)"                       => "location-1-1-20-9-2",
    "West (British Era)"                       => "location-1-1-20-9-3",
    "South (British Era)"                      => "location-1-1-20-9-4",
    "Central (British Era)"                    => "location-1-1-20-9-5",
    "Postal Province"                          => "location-1-1-21-1",
    "Postal District"                          => "location-1-1-21-1-1",
    "Main Post Office"                         => "location-1-1-21-1-1-1",
    "Sub Post Office"                          => "location-1-1-21-1-1-1-1",
    "Agricultural District Zone"               => "location-1-1-22-1",
    "Agrarian Service Area"                    => "location-1-1-22-1-1",
    "Health Province"                          => "location-1-1-5-1",
    "Health District"                          => "location-1-1-5-1-1",
    "Medical Officer of Health Area"           => "location-1-1-5-1-1-1",
    "Public Health Inspectorate Area"          => "location-1-1-5-1-1-1-1",
    "Family Health Worker Area"                => "location-1-1-5-1-1-1-1-1",
    "Forest Division"                          => "location-1-1-6-1-1",
    "Forest Range"                             => "location-1-1-6-1-1-1",
    "Forest Beat"                              => "location-1-1-6-1-1-1-1",
    "Forest Fields"                            => "location-1-1-6-1-1-1-1-1",
    "DIG Division"                             => "location-1-1-2-1-1-1",
    "SDIG Division"                            => "location-1-1-2-1-1",
    "Police Division (Police Station)"         => "location-1-1-2-1-1-1-1-1",
    "Assistant Director of Wildlife Area"      => "location-1-1-7-1",
    "Wildlife Range"                           => "location-1-1-7-1-1",
    "Wildlife Beat"                            => "location-1-1-7-1-1-1",
];

$updatedCount = 0;
$skippedCount = 0;
$notFoundCount = 0;
$conflictCount = 0;

// Build a lookup: lowercase name -> slug (last one wins for duplicates)
$prodLookup = [];
foreach ($prodData as $row) {
    $prodLookup[strtolower(trim($row['name_en']))] = $row['slug'];
}

// Get all local categories
$allLocal = Category::all();

foreach ($allLocal as $cat) {
    $localNameLower = strtolower(trim($cat->name_en));
    $newSlug = null;
    $matchType = null;

    // Try exact case-insensitive match from prod data
    if (isset($prodLookup[$localNameLower])) {
        $newSlug = $prodLookup[$localNameLower];
        $matchType = 'PROD';
    }
    // Try manual mapping (exact name match)
    elseif (isset($manualMappings[$cat->name_en])) {
        $newSlug = $manualMappings[$cat->name_en];
        $matchType = 'MANUAL';
    }
    else {
        $notFoundCount++;
        continue;
    }

    if ($cat->slug === $newSlug) {
        $skippedCount++;
        continue;
    }

    // Check if the new slug already exists on a DIFFERENT category
    $existingWithSlug = Category::where('slug', $newSlug)->where('id', '!=', $cat->id)->first();
    if ($existingWithSlug) {
        echo "⚠ [CONFLICT] '{$cat->name_en}' => {$newSlug} — already used by [{$existingWithSlug->id}] '{$existingWithSlug->name_en}'\n";
        $conflictCount++;
        continue;
    }

    $cat->slug = $newSlug;
    $cat->save();
    echo "✓ [{$matchType}] '{$cat->name_en}' => {$newSlug}\n";
    $updatedCount++;
}

echo "\n========================================\n";
echo "✓ Updated: {$updatedCount}\n";
echo "- Already correct / skipped: {$skippedCount}\n";
echo "⚠ Conflicts (slug used by another cat): {$conflictCount}\n";
echo "✗ Not matched in prod data: {$notFoundCount}\n";

// Show categories still with non-location slugs
$remaining = Category::where('slug', 'not like', 'location-%')->get(['id', 'name_en', 'slug']);
echo "\n=== STILL WITH NON-LOCATION SLUGS: " . $remaining->count() . " ===\n";
foreach ($remaining as $c) {
    echo "  [{$c->id}] {$c->name_en} => {$c->slug}\n";
}
