import { useLanguage } from '../../context/LanguageContext';

/**
 * Copy for the contributor experience. Sinhala is the app's default language,
 * so every string ships in all three languages. `{name}` style placeholders
 * are filled by `fill()`.
 */
const en = {
  navContribute: 'Contribute',
  navMyContributions: 'My contributions',
  navHome: 'Village page',
  navChangeRegion: 'Change village',
  navLogout: 'Log out',

  greetingMorning: 'Good morning',
  greetingAfternoon: 'Good afternoon',
  greetingEvening: 'Good evening',
  heroTitle: 'Help map {village}',
  heroTitleNoVillage: 'Help map your village',
  heroBody:
    'Ceylonica is built by the people who live here. Add what you know about your village — places, services, land and businesses — and help complete its record for everyone.',
  heroBodyNoVillage: 'Choose your village to see what is still missing and start contributing.',
  chooseVillage: 'Choose your village',
  chooseVillageHint: 'Pick your district, DS division and Grama Niladhari division. You can change it any time.',

  progressTitle: 'Village record',
  progressComplete: '{pct}% mapped',
  progressTopics: '{covered} of {total} topics have data',
  progressCategories: '{covered} of {total} areas started',
  statRecords: 'Records',
  statInReview: 'In review',
  statContributors: 'Contributors',
  statBusinesses: 'Businesses',
  progressError: 'Could not load village progress.',
  retry: 'Retry',

  startContributing: 'Start contributing',
  registerBusiness: 'Register a business',
  openVillagePage: 'View village page',

  myImpactTitle: 'Your contributions',
  myImpactEmpty: 'You have not added anything yet — your first contribution takes about two minutes.',
  myImpactTotal: 'Added',
  myImpactApproved: 'Approved',
  myImpactReview: 'In review',
  viewAll: 'View all',

  whatToAddTitle: 'What can you add?',
  whatToAddBody: 'Pick an area you know. Areas marked “Needs data” have nothing recorded for your village yet.',
  filterAll: 'All areas',
  filterNeeds: 'Needs data',
  searchPlaceholder: 'Search for something to add',
  needsData: 'Needs data',
  beFirst: 'Be the first to add',
  recordsInVillage: '{n} in your village',
  recordsInVillageOne: '1 in your village',
  topicsCount: '{n} topics',
  noResults: 'No matching topics',
  categoriesError: 'Topics could not be loaded. Check your connection and try again.',
  noCategories: 'Nothing to contribute to yet.',

  formTitle: 'Add to {category}',
  formSubtitle: 'For {village}. Your submission is reviewed before it appears publicly.',
  formSubtitleNoVillage: 'Your submission is reviewed before it appears publicly.',
  stepLocation: 'Where is it?',
  stepDetails: 'What is it?',
  stepEvidence: 'Photo and exact location',
  optional: 'Optional',
  province: 'Province',
  district: 'District',
  dsDivision: 'DS division',
  gnDivision: 'GN division',
  nameLabel: 'Name',
  nameHelper: 'Search to update an existing entry, or type a new name.',
  nameSi: 'Name in Sinhala',
  nameTa: 'Name in Tamil',
  mobile: 'Contact number',
  contactPerson: 'Contact person',
  address: 'Address',
  captureLocation: 'Use my current location',
  locationCaptured: 'Location captured',
  locationMismatch:
    'Your current position is outside the selected GN division. We will still save it, but a reviewer will check it.',
  uploadPhoto: 'Add a photo',
  replacePhoto: 'Replace photo',
  uploading: 'Uploading…',
  submit: 'Submit contribution',
  submitting: 'Submitting…',
  updatingExisting: 'You are suggesting an update to “{name}”.',
  newEntryInstead: 'Add as a new entry instead',
  errLocation: 'Choose the province, district, DS division and GN division.',
  errName: 'Enter a name in at least one language.',
  errSession: 'Your session expired. Sign in again to be credited, or submit anonymously.',
  signInToBeCredited: 'Sign in so this contribution is credited to you.',
  signIn: 'Sign in',
  geoConfirmTitle: 'Use your current location?',
  geoConfirmBody: 'Only do this if you are standing at the place you are adding.',
  geoConfirmYes: 'Yes, use it',
  geoConfirmNo: 'Not now',

  thanksTitle: 'Thank you for contributing',
  thanksBody: 'Your entry for {category} is now with a reviewer. Once approved it becomes part of {village}’s public record.',
  thanksBodyNoVillage: 'Your entry for {category} is now with a reviewer. Once approved it becomes part of the public record.',
  thanksReg: 'Reference number',
  thanksCredited: 'Credited to your account',
  thanksAnonymous: 'Submitted anonymously',
  addAnother: 'Add another',
  backToTopics: 'Back to topics',

  myTitle: 'My contributions',
  mySubtitle: 'Everything you have added to Ceylonica, and where it is in review.',
  myEmptyTitle: 'Nothing here yet',
  myEmptyBody: 'Add a place, a service or a business from your village. It takes about two minutes.',
  myError: 'Your contributions could not be loaded.',
  myFilterAll: 'All',
  myFilterReview: 'In review',
  myFilterApproved: 'Approved',
  myFilterDrafts: 'Drafts',
  statusPending: 'In review',
  statusSubmitted: 'In review',
  statusApproved: 'Approved',
  statusRejected: 'Not accepted',
  statusDraft: 'Draft',
  kindBusiness: 'Business survey',
  updateProposal: 'Update',
  untitled: 'Untitled entry',
  continueDraft: 'Continue',
  villagesCount: 'Villages',

  bannerTitle: 'This record is built by people like you',
  bannerBody: '{village} is {pct}% mapped. Add what you know about your village and help complete it.',
  bannerBodyNoData: 'Nothing has been recorded for {village} yet. Be the first to add what you know.',
  bannerCta: 'Contribute',
  bannerCtaGuest: 'Join and contribute',

  navRapidFire: 'Rapid fire',
  rfTitle: 'Rapid fire',
  rfTagline: 'Yes or no — is it in {village}? Answer fast; every answer maps your village.',
  rfTaglineNoVillage: 'Choose your village first, then answer as many as you can.',
  rfRuleCards: '{n} questions',
  rfRuleSeconds: '{n} seconds each',
  rfRuleBonus: 'Speed and streak bonuses',
  rfChooseDeck: 'Choose a deck',
  rfMix: 'Quick mix',
  rfMixHint: 'A bit of everything',
  rfLeft: '{n} left',
  rfDone: 'All done',
  rfStart: 'Start',
  rfDecksError: 'Decks could not be loaded.',
  rfKeysHint: 'Keyboard: ← No · → Yes · ↓ Not sure. On a phone, swipe the card.',
  rfGo: 'Go!',
  rfQuestion: 'Is this in {village}?',
  rfYes: 'Yes',
  rfNo: 'No',
  rfUnsure: 'Not sure',
  rfScore: 'Score',
  rfStreak: 'Streak',
  rfQuit: 'End round',
  rfTooFast: 'Too fast — take a second to read each one.',
  rfTimeUp: 'Time is up',
  rfSaving: 'Saving…',
  rfExpired: 'This round expired. Start a new one.',
  rfSaveError: 'Some answers could not be saved. Check your connection.',
  rfResultsTitle: 'Round complete!',
  rfResultsBody: 'You checked {n} topics for {village}.',
  rfBestStreak: 'Best streak',
  rfAnswered: 'Answered',
  rfSkipped: 'Skipped',
  rfYesTitle: 'You said these are in your village',
  rfYesBody: 'Add details so others can find them — this is where your village record really grows.',
  rfAddDetails: 'Add details',
  rfPlayAgain: 'Play again',
  rfOtherDeck: 'Choose another deck',
  rfBackToContribute: 'Back to contribute',
  rfRankScout: 'Village scout',
  rfRankMapper: 'Village mapper',
  rfRankExpert: 'Village expert',
  rfRankLegend: 'Village legend',
  rfPromoTitle: 'Got a minute? Play rapid fire',
  rfPromoBody: 'Quick yes-or-no questions about your village. Fast, fun, and every answer counts.',
  rfPromoCta: 'Play now',
  statChecked: 'Checked',
};

type Copy = typeof en;

const si: Copy = {
  navContribute: 'දායක වන්න',
  navMyContributions: 'මගේ දායකත්වය',
  navHome: 'ගම්මාන පිටුව',
  navChangeRegion: 'ගම්මානය වෙනස් කරන්න',
  navLogout: 'ඉවත් වන්න',

  greetingMorning: 'සුබ උදෑසනක්',
  greetingAfternoon: 'සුබ දහවලක්',
  greetingEvening: 'සුබ සන්ධ්‍යාවක්',
  heroTitle: '{village} සිතියම්ගත කිරීමට උදව් වන්න',
  heroTitleNoVillage: 'ඔබේ ගම්මානය සිතියම්ගත කිරීමට උදව් වන්න',
  heroBody:
    'සෙලෝනිකා ගොඩනැගෙන්නේ මෙහි ජීවත් වන ජනතාව විසිනි. ඔබේ ගම්මානය ගැන ඔබ දන්නා දේ — ස්ථාන, සේවා, ඉඩම් සහ ව්‍යාපාර — එක් කර, සැමට වැදගත් වන එහි වාර්තාව සම්පූර්ණ කිරීමට උදව් වන්න.',
  heroBodyNoVillage: 'තවමත් නොමැති දේ බලා දායක වීම ආරම්භ කිරීමට ඔබේ ගම්මානය තෝරන්න.',
  chooseVillage: 'ඔබේ ගම්මානය තෝරන්න',
  chooseVillageHint: 'දිස්ත්‍රික්කය, ප්‍රාදේශීය ලේකම් කොට්ඨාසය සහ ග්‍රාම නිලධාරී වසම තෝරන්න. ඕනෑම වේලාවක වෙනස් කළ හැක.',

  progressTitle: 'ගම්මාන වාර්තාව',
  progressComplete: '{pct}% සිතියම්ගත කර ඇත',
  progressTopics: 'මාතෘකා {total} න් {covered} ක දත්ත ඇත',
  progressCategories: 'අංශ {total} න් {covered} ක් ආරම්භ කර ඇත',
  statRecords: 'වාර්තා',
  statInReview: 'සමාලෝචනයේ',
  statContributors: 'දායකයින්',
  statBusinesses: 'ව්‍යාපාර',
  progressError: 'ගම්මාන ප්‍රගතිය පූරණය කළ නොහැකි විය.',
  retry: 'නැවත උත්සාහ කරන්න',

  startContributing: 'දායක වීම ආරම්භ කරන්න',
  registerBusiness: 'ව්‍යාපාරයක් ලියාපදිංචි කරන්න',
  openVillagePage: 'ගම්මාන පිටුව බලන්න',

  myImpactTitle: 'ඔබේ දායකත්වය',
  myImpactEmpty: 'ඔබ තවම කිසිවක් එක් කර නැත — ඔබේ පළමු දායකත්වයට මිනිත්තු දෙකක් පමණ ගත වේ.',
  myImpactTotal: 'එක් කළ',
  myImpactApproved: 'අනුමත',
  myImpactReview: 'සමාලෝචනයේ',
  viewAll: 'සියල්ල බලන්න',

  whatToAddTitle: 'ඔබට එක් කළ හැක්කේ කුමක්ද?',
  whatToAddBody: 'ඔබ දන්නා අංශයක් තෝරන්න. “දත්ත අවශ්‍යයි” ලෙස සලකුණු කළ අංශවල ඔබේ ගම්මානය සඳහා තවම කිසිවක් වාර්තා කර නැත.',
  filterAll: 'සියලු අංශ',
  filterNeeds: 'දත්ත අවශ්‍යයි',
  searchPlaceholder: 'එක් කිරීමට යමක් සොයන්න',
  needsData: 'දත්ත අවශ්‍යයි',
  beFirst: 'පළමුවැන්නා වන්න',
  recordsInVillage: 'ඔබේ ගම්මානයේ {n}',
  recordsInVillageOne: 'ඔබේ ගම්මානයේ 1',
  topicsCount: 'මාතෘකා {n}',
  noResults: 'ගැළපෙන මාතෘකා නැත',
  categoriesError: 'මාතෘකා පූරණය කළ නොහැකි විය. සම්බන්ධතාවය පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
  noCategories: 'දායක වීමට තවම කිසිවක් නැත.',

  formTitle: '{category} වෙත එක් කරන්න',
  formSubtitle: '{village} සඳහා. ඔබේ ඉදිරිපත් කිරීම ප්‍රසිද්ධියේ පෙන්වීමට පෙර සමාලෝචනය කෙරේ.',
  formSubtitleNoVillage: 'ඔබේ ඉදිරිපත් කිරීම ප්‍රසිද්ධියේ පෙන්වීමට පෙර සමාලෝචනය කෙරේ.',
  stepLocation: 'එය පිහිටා ඇත්තේ කොහේද?',
  stepDetails: 'එය කුමක්ද?',
  stepEvidence: 'ඡායාරූපය සහ නිවැරදි ස්ථානය',
  optional: 'අත්‍යවශ්‍ය නොවේ',
  province: 'පළාත',
  district: 'දිස්ත්‍රික්කය',
  dsDivision: 'ප්‍රා.ලේ. කොට්ඨාසය',
  gnDivision: 'ග්‍රා.නි. වසම',
  nameLabel: 'නම',
  nameHelper: 'පවතින ඇතුළත් කිරීමක් යාවත්කාලීන කිරීමට සොයන්න, නැතහොත් නව නමක් ටයිප් කරන්න.',
  nameSi: 'සිංහලෙන් නම',
  nameTa: 'දෙමළෙන් නම',
  mobile: 'සම්බන්ධතා අංකය',
  contactPerson: 'සම්බන්ධ විය යුතු පුද්ගලයා',
  address: 'ලිපිනය',
  captureLocation: 'මගේ වත්මන් ස්ථානය භාවිත කරන්න',
  locationCaptured: 'ස්ථානය ලබා ගන්නා ලදී',
  locationMismatch:
    'ඔබේ වත්මන් ස්ථානය තෝරාගත් ග්‍රා.නි. වසමෙන් පිටත ය. අපි එය සුරකින නමුත් සමාලෝචකයෙකු එය පරීක්ෂා කරනු ඇත.',
  uploadPhoto: 'ඡායාරූපයක් එක් කරන්න',
  replacePhoto: 'ඡායාරූපය වෙනස් කරන්න',
  uploading: 'උඩුගත කරමින්…',
  submit: 'දායකත්වය ඉදිරිපත් කරන්න',
  submitting: 'ඉදිරිපත් කරමින්…',
  updatingExisting: 'ඔබ “{name}” සඳහා යාවත්කාලීනයක් යෝජනා කරයි.',
  newEntryInstead: 'ඒ වෙනුවට නව ඇතුළත් කිරීමක් ලෙස එක් කරන්න',
  errLocation: 'පළාත, දිස්ත්‍රික්කය, ප්‍රා.ලේ. කොට්ඨාසය සහ ග්‍රා.නි. වසම තෝරන්න.',
  errName: 'අවම වශයෙන් එක් භාෂාවකින් නමක් ඇතුළත් කරන්න.',
  errSession: 'ඔබේ සැසිය කල් ඉකුත් විය. ගෞරවය ලැබීමට නැවත පුරන්න, නැතහොත් නිර්නාමිකව ඉදිරිපත් කරන්න.',
  signInToBeCredited: 'මෙම දායකත්වය ඔබට හිමි වීමට පුරන්න.',
  signIn: 'පුරන්න',
  geoConfirmTitle: 'ඔබේ වත්මන් ස්ථානය භාවිත කරන්නද?',
  geoConfirmBody: 'ඔබ එක් කරන ස්ථානයේ සිටින්නේ නම් පමණක් මෙය කරන්න.',
  geoConfirmYes: 'ඔව්, භාවිත කරන්න',
  geoConfirmNo: 'දැන් නොවේ',

  thanksTitle: 'දායක වීම ගැන ස්තූතියි',
  thanksBody: '{category} සඳහා ඔබේ ඇතුළත් කිරීම දැන් සමාලෝචකයෙකු වෙත ඇත. අනුමත වූ පසු එය {village} හි ප්‍රසිද්ධ වාර්තාවේ කොටසක් වේ.',
  thanksBodyNoVillage: '{category} සඳහා ඔබේ ඇතුළත් කිරීම දැන් සමාලෝචකයෙකු වෙත ඇත. අනුමත වූ පසු එය ප්‍රසිද්ධ වාර්තාවේ කොටසක් වේ.',
  thanksReg: 'යොමු අංකය',
  thanksCredited: 'ඔබේ ගිණුමට හිමි කරන ලදී',
  thanksAnonymous: 'නිර්නාමිකව ඉදිරිපත් කරන ලදී',
  addAnother: 'තවත් එකක් එක් කරන්න',
  backToTopics: 'මාතෘකා වෙත ආපසු',

  myTitle: 'මගේ දායකත්වය',
  mySubtitle: 'ඔබ සෙලෝනිකා වෙත එක් කළ සියල්ල සහ ඒවායේ සමාලෝචන තත්ත්වය.',
  myEmptyTitle: 'තවම මෙහි කිසිවක් නැත',
  myEmptyBody: 'ඔබේ ගම්මානයෙන් ස්ථානයක්, සේවාවක් හෝ ව්‍යාපාරයක් එක් කරන්න. මිනිත්තු දෙකක් පමණ ගත වේ.',
  myError: 'ඔබේ දායකත්වය පූරණය කළ නොහැකි විය.',
  myFilterAll: 'සියල්ල',
  myFilterReview: 'සමාලෝචනයේ',
  myFilterApproved: 'අනුමත',
  myFilterDrafts: 'කෙටුම්පත්',
  statusPending: 'සමාලෝචනයේ',
  statusSubmitted: 'සමාලෝචනයේ',
  statusApproved: 'අනුමත',
  statusRejected: 'පිළිගත්තේ නැත',
  statusDraft: 'කෙටුම්පත',
  kindBusiness: 'ව්‍යාපාර සමීක්ෂණය',
  updateProposal: 'යාවත්කාලීනය',
  untitled: 'නම් නොකළ ඇතුළත් කිරීම',
  continueDraft: 'දිගටම කරන්න',
  villagesCount: 'ගම්මාන',

  bannerTitle: 'මෙම වාර්තාව ගොඩනැගෙන්නේ ඔබ වැනි අය විසිනි',
  bannerBody: '{village} {pct}% ක් සිතියම්ගත කර ඇත. ඔබේ ගම්මානය ගැන ඔබ දන්නා දේ එක් කර එය සම්පූර්ණ කිරීමට උදව් වන්න.',
  bannerBodyNoData: '{village} සඳහා තවම කිසිවක් වාර්තා කර නැත. ඔබ දන්නා දේ එක් කරන පළමුවැන්නා වන්න.',
  bannerCta: 'දායක වන්න',
  bannerCtaGuest: 'සම්බන්ධ වී දායක වන්න',

  navRapidFire: 'ඉක්මන් ප්‍රශ්න',
  rfTitle: 'ඉක්මන් ප්‍රශ්න',
  rfTagline: 'ඔව් හෝ නැත — එය {village} හි තිබේද? ඉක්මනින් පිළිතුරු දෙන්න; සෑම පිළිතුරක්ම ඔබේ ගම්මානය සිතියම්ගත කරයි.',
  rfTaglineNoVillage: 'පළමුව ඔබේ ගම්මානය තෝරා, හැකි තරම් ප්‍රශ්නවලට පිළිතුරු දෙන්න.',
  rfRuleCards: 'ප්‍රශ්න {n}',
  rfRuleSeconds: 'එකකට තත්පර {n}',
  rfRuleBonus: 'වේගය සහ අඛණ්ඩතාව සඳහා ප්‍රසාද ලකුණු',
  rfChooseDeck: 'කාණ්ඩයක් තෝරන්න',
  rfMix: 'ඉක්මන් මිශ්‍රණය',
  rfMixHint: 'සෑම දෙයකින්ම ටිකක්',
  rfLeft: '{n} ක් ඉතිරියි',
  rfDone: 'සියල්ල නිමයි',
  rfStart: 'අරඹන්න',
  rfDecksError: 'කාණ්ඩ පූරණය කළ නොහැකි විය.',
  rfKeysHint: 'යතුරු පුවරුව: ← නැත · → ඔව් · ↓ විශ්වාස නැත. දුරකථනයේ කාඩ්පත ස්වයිප් කරන්න.',
  rfGo: 'යමු!',
  rfQuestion: 'මෙය {village} හි තිබේද?',
  rfYes: 'ඔව්',
  rfNo: 'නැත',
  rfUnsure: 'විශ්වාස නැත',
  rfScore: 'ලකුණු',
  rfStreak: 'අඛණ්ඩව',
  rfQuit: 'වටය අවසන් කරන්න',
  rfTooFast: 'ඉතා වේගවත් — සෑම එකක්ම කියවීමට තත්පරයක් ගන්න.',
  rfTimeUp: 'කාලය අවසන්',
  rfSaving: 'සුරකිමින්…',
  rfExpired: 'මෙම වටය කල් ඉකුත් විය. නව එකක් අරඹන්න.',
  rfSaveError: 'සමහර පිළිතුරු සුරැකිය නොහැකි විය. සම්බන්ධතාවය පරීක්ෂා කරන්න.',
  rfResultsTitle: 'වටය නිමයි!',
  rfResultsBody: 'ඔබ {village} සඳහා මාතෘකා {n} ක් පරීක්ෂා කළා.',
  rfBestStreak: 'හොඳම අඛණ්ඩතාව',
  rfAnswered: 'පිළිතුරු දුන්',
  rfSkipped: 'මඟ හැරුණු',
  rfYesTitle: 'ඔබේ ගම්මානයේ ඇති බව ඔබ කී දේ',
  rfYesBody: 'අන් අයට ඒවා සොයා ගැනීමට විස්තර එක් කරන්න — ඔබේ ගම්මාන වාර්තාව සැබවින්ම වර්ධනය වන්නේ මෙතැනිනි.',
  rfAddDetails: 'විස්තර එක් කරන්න',
  rfPlayAgain: 'නැවත ක්‍රීඩා කරන්න',
  rfOtherDeck: 'වෙනත් කාණ්ඩයක් තෝරන්න',
  rfBackToContribute: 'දායක වීම වෙත ආපසු',
  rfRankScout: 'ගම්මාන ගවේෂක',
  rfRankMapper: 'ගම්මාන සිතියම්කරු',
  rfRankExpert: 'ගම්මාන විශේෂඥ',
  rfRankLegend: 'ගම්මාන වීරයා',
  rfPromoTitle: 'මිනිත්තුවක් තිබේද? ඉක්මන් ප්‍රශ්න ක්‍රීඩා කරන්න',
  rfPromoBody: 'ඔබේ ගම්මානය ගැන ඉක්මන් ඔව්-නැත ප්‍රශ්න. ඉක්මන්, විනෝදජනක, සෑම පිළිතුරක්ම වැදගත්.',
  rfPromoCta: 'දැන් ක්‍රීඩා කරන්න',
  statChecked: 'පරීක්ෂා කළ',
};

const ta: Copy = {
  navContribute: 'பங்களியுங்கள்',
  navMyContributions: 'எனது பங்களிப்புகள்',
  navHome: 'கிராமப் பக்கம்',
  navChangeRegion: 'கிராமத்தை மாற்று',
  navLogout: 'வெளியேறு',

  greetingMorning: 'காலை வணக்கம்',
  greetingAfternoon: 'மதிய வணக்கம்',
  greetingEvening: 'மாலை வணக்கம்',
  heroTitle: '{village} ஐ வரைபடமாக்க உதவுங்கள்',
  heroTitleNoVillage: 'உங்கள் கிராமத்தை வரைபடமாக்க உதவுங்கள்',
  heroBody:
    'சிலோனிகா இங்கு வாழும் மக்களால் உருவாக்கப்படுகிறது. உங்கள் கிராமத்தைப் பற்றி உங்களுக்குத் தெரிந்தவற்றை — இடங்கள், சேவைகள், நிலம் மற்றும் வணிகங்கள் — சேர்த்து, அனைவருக்குமான அதன் பதிவை நிறைவு செய்ய உதவுங்கள்.',
  heroBodyNoVillage: 'இன்னும் விடுபட்டவற்றைப் பார்த்து பங்களிக்கத் தொடங்க உங்கள் கிராமத்தைத் தேர்ந்தெடுக்கவும்.',
  chooseVillage: 'உங்கள் கிராமத்தைத் தேர்ந்தெடுக்கவும்',
  chooseVillageHint: 'மாவட்டம், பிரதேச செயலகப் பிரிவு மற்றும் கிராம அலுவலர் பிரிவைத் தேர்ந்தெடுக்கவும். எப்போது வேண்டுமானாலும் மாற்றலாம்.',

  progressTitle: 'கிராமப் பதிவு',
  progressComplete: '{pct}% வரைபடமாக்கப்பட்டது',
  progressTopics: '{total} தலைப்புகளில் {covered} க்கு தரவு உள்ளது',
  progressCategories: '{total} பகுதிகளில் {covered} தொடங்கப்பட்டன',
  statRecords: 'பதிவுகள்',
  statInReview: 'மதிப்பாய்வில்',
  statContributors: 'பங்களிப்பாளர்கள்',
  statBusinesses: 'வணிகங்கள்',
  progressError: 'கிராம முன்னேற்றத்தை ஏற்ற முடியவில்லை.',
  retry: 'மீண்டும் முயற்சி',

  startContributing: 'பங்களிக்கத் தொடங்குங்கள்',
  registerBusiness: 'வணிகத்தைப் பதிவு செய்யுங்கள்',
  openVillagePage: 'கிராமப் பக்கத்தைப் பார்',

  myImpactTitle: 'உங்கள் பங்களிப்புகள்',
  myImpactEmpty: 'நீங்கள் இன்னும் எதையும் சேர்க்கவில்லை — உங்கள் முதல் பங்களிப்புக்கு சுமார் இரண்டு நிமிடங்கள் ஆகும்.',
  myImpactTotal: 'சேர்த்தவை',
  myImpactApproved: 'அங்கீகரிக்கப்பட்டவை',
  myImpactReview: 'மதிப்பாய்வில்',
  viewAll: 'அனைத்தையும் பார்',

  whatToAddTitle: 'நீங்கள் எதைச் சேர்க்கலாம்?',
  whatToAddBody: 'உங்களுக்குத் தெரிந்த பகுதியைத் தேர்ந்தெடுக்கவும். “தரவு தேவை” எனக் குறிக்கப்பட்ட பகுதிகளில் உங்கள் கிராமத்திற்கு இன்னும் எதுவும் பதிவு செய்யப்படவில்லை.',
  filterAll: 'அனைத்துப் பகுதிகளும்',
  filterNeeds: 'தரவு தேவை',
  searchPlaceholder: 'சேர்க்க ஏதாவது தேடுங்கள்',
  needsData: 'தரவு தேவை',
  beFirst: 'முதலில் சேர்ப்பவராக இருங்கள்',
  recordsInVillage: 'உங்கள் கிராமத்தில் {n}',
  recordsInVillageOne: 'உங்கள் கிராமத்தில் 1',
  topicsCount: '{n} தலைப்புகள்',
  noResults: 'பொருந்தும் தலைப்புகள் இல்லை',
  categoriesError: 'தலைப்புகளை ஏற்ற முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  noCategories: 'பங்களிக்க இன்னும் எதுவும் இல்லை.',

  formTitle: '{category} இல் சேர்க்கவும்',
  formSubtitle: '{village} க்காக. பொதுவில் தோன்றும் முன் உங்கள் சமர்ப்பிப்பு மதிப்பாய்வு செய்யப்படும்.',
  formSubtitleNoVillage: 'பொதுவில் தோன்றும் முன் உங்கள் சமர்ப்பிப்பு மதிப்பாய்வு செய்யப்படும்.',
  stepLocation: 'அது எங்கே உள்ளது?',
  stepDetails: 'அது என்ன?',
  stepEvidence: 'புகைப்படம் மற்றும் சரியான இடம்',
  optional: 'விருப்பத்தேர்வு',
  province: 'மாகாணம்',
  district: 'மாவட்டம்',
  dsDivision: 'பி.செ. பிரிவு',
  gnDivision: 'கி.அ. பிரிவு',
  nameLabel: 'பெயர்',
  nameHelper: 'ஏற்கனவே உள்ள பதிவைப் புதுப்பிக்கத் தேடுங்கள், அல்லது புதிய பெயரைத் தட்டச்சு செய்யுங்கள்.',
  nameSi: 'சிங்களத்தில் பெயர்',
  nameTa: 'தமிழில் பெயர்',
  mobile: 'தொடர்பு எண்',
  contactPerson: 'தொடர்பு நபர்',
  address: 'முகவரி',
  captureLocation: 'எனது தற்போதைய இருப்பிடத்தைப் பயன்படுத்து',
  locationCaptured: 'இருப்பிடம் பெறப்பட்டது',
  locationMismatch:
    'உங்கள் தற்போதைய இருப்பிடம் தேர்ந்தெடுத்த கி.அ. பிரிவுக்கு வெளியே உள்ளது. நாங்கள் அதைச் சேமிப்போம், ஆனால் ஒரு மதிப்பாய்வாளர் சரிபார்ப்பார்.',
  uploadPhoto: 'புகைப்படம் சேர்',
  replacePhoto: 'புகைப்படத்தை மாற்று',
  uploading: 'பதிவேற்றுகிறது…',
  submit: 'பங்களிப்பைச் சமர்ப்பி',
  submitting: 'சமர்ப்பிக்கிறது…',
  updatingExisting: 'நீங்கள் “{name}” க்கு ஒரு புதுப்பிப்பைப் பரிந்துரைக்கிறீர்கள்.',
  newEntryInstead: 'பதிலாக புதிய பதிவாகச் சேர்',
  errLocation: 'மாகாணம், மாவட்டம், பி.செ. பிரிவு மற்றும் கி.அ. பிரிவைத் தேர்ந்தெடுக்கவும்.',
  errName: 'குறைந்தது ஒரு மொழியிலாவது பெயரை உள்ளிடவும்.',
  errSession: 'உங்கள் அமர்வு காலாவதியானது. உங்களுக்குப் பெருமை சேர மீண்டும் உள்நுழையவும், அல்லது அநாமதேயமாகச் சமர்ப்பிக்கவும்.',
  signInToBeCredited: 'இந்தப் பங்களிப்பு உங்களுக்குச் சேர உள்நுழையவும்.',
  signIn: 'உள்நுழை',
  geoConfirmTitle: 'உங்கள் தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவா?',
  geoConfirmBody: 'நீங்கள் சேர்க்கும் இடத்தில் நிற்கிறீர்கள் என்றால் மட்டுமே இதைச் செய்யுங்கள்.',
  geoConfirmYes: 'ஆம், பயன்படுத்து',
  geoConfirmNo: 'இப்போது வேண்டாம்',

  thanksTitle: 'பங்களித்தமைக்கு நன்றி',
  thanksBody: '{category} க்கான உங்கள் பதிவு இப்போது மதிப்பாய்வாளரிடம் உள்ளது. அங்கீகரிக்கப்பட்டதும் அது {village} இன் பொதுப் பதிவின் ஒரு பகுதியாகும்.',
  thanksBodyNoVillage: '{category} க்கான உங்கள் பதிவு இப்போது மதிப்பாய்வாளரிடம் உள்ளது. அங்கீகரிக்கப்பட்டதும் அது பொதுப் பதிவின் ஒரு பகுதியாகும்.',
  thanksReg: 'குறிப்பு எண்',
  thanksCredited: 'உங்கள் கணக்கில் சேர்க்கப்பட்டது',
  thanksAnonymous: 'அநாமதேயமாகச் சமர்ப்பிக்கப்பட்டது',
  addAnother: 'இன்னொன்றைச் சேர்',
  backToTopics: 'தலைப்புகளுக்குத் திரும்பு',

  myTitle: 'எனது பங்களிப்புகள்',
  mySubtitle: 'நீங்கள் சிலோனிகாவில் சேர்த்த அனைத்தும், மற்றும் அவற்றின் மதிப்பாய்வு நிலை.',
  myEmptyTitle: 'இங்கு இன்னும் எதுவும் இல்லை',
  myEmptyBody: 'உங்கள் கிராமத்திலிருந்து ஒரு இடம், சேவை அல்லது வணிகத்தைச் சேர்க்கவும். சுமார் இரண்டு நிமிடங்கள் ஆகும்.',
  myError: 'உங்கள் பங்களிப்புகளை ஏற்ற முடியவில்லை.',
  myFilterAll: 'அனைத்தும்',
  myFilterReview: 'மதிப்பாய்வில்',
  myFilterApproved: 'அங்கீகரிக்கப்பட்டவை',
  myFilterDrafts: 'வரைவுகள்',
  statusPending: 'மதிப்பாய்வில்',
  statusSubmitted: 'மதிப்பாய்வில்',
  statusApproved: 'அங்கீகரிக்கப்பட்டது',
  statusRejected: 'ஏற்கப்படவில்லை',
  statusDraft: 'வரைவு',
  kindBusiness: 'வணிகக் கணக்கெடுப்பு',
  updateProposal: 'புதுப்பிப்பு',
  untitled: 'பெயரிடப்படாத பதிவு',
  continueDraft: 'தொடரவும்',
  villagesCount: 'கிராமங்கள்',

  bannerTitle: 'இந்தப் பதிவு உங்களைப் போன்றவர்களால் உருவாக்கப்படுகிறது',
  bannerBody: '{village} {pct}% வரைபடமாக்கப்பட்டுள்ளது. உங்கள் கிராமத்தைப் பற்றி உங்களுக்குத் தெரிந்தவற்றைச் சேர்த்து அதை நிறைவு செய்ய உதவுங்கள்.',
  bannerBodyNoData: '{village} க்கு இன்னும் எதுவும் பதிவு செய்யப்படவில்லை. உங்களுக்குத் தெரிந்தவற்றை முதலில் சேர்ப்பவராக இருங்கள்.',
  bannerCta: 'பங்களியுங்கள்',
  bannerCtaGuest: 'இணைந்து பங்களியுங்கள்',

  navRapidFire: 'விரைவுக் கேள்விகள்',
  rfTitle: 'விரைவுக் கேள்விகள்',
  rfTagline: 'ஆம் அல்லது இல்லை — இது {village} இல் உள்ளதா? விரைவாகப் பதிலளியுங்கள்; ஒவ்வொரு பதிலும் உங்கள் கிராமத்தை வரைபடமாக்குகிறது.',
  rfTaglineNoVillage: 'முதலில் உங்கள் கிராமத்தைத் தேர்ந்தெடுத்து, முடிந்தவரை பதிலளியுங்கள்.',
  rfRuleCards: '{n} கேள்விகள்',
  rfRuleSeconds: 'ஒவ்வொன்றுக்கும் {n} வினாடிகள்',
  rfRuleBonus: 'வேகம் மற்றும் தொடர் போனஸ்',
  rfChooseDeck: 'ஒரு தொகுப்பைத் தேர்ந்தெடுக்கவும்',
  rfMix: 'விரைவுக் கலவை',
  rfMixHint: 'எல்லாவற்றிலும் கொஞ்சம்',
  rfLeft: '{n} மீதம்',
  rfDone: 'அனைத்தும் முடிந்தது',
  rfStart: 'தொடங்கு',
  rfDecksError: 'தொகுப்புகளை ஏற்ற முடியவில்லை.',
  rfKeysHint: 'விசைப்பலகை: ← இல்லை · → ஆம் · ↓ உறுதியில்லை. தொலைபேசியில் அட்டையை ஸ்வைப் செய்யவும்.',
  rfGo: 'தொடங்கு!',
  rfQuestion: 'இது {village} இல் உள்ளதா?',
  rfYes: 'ஆம்',
  rfNo: 'இல்லை',
  rfUnsure: 'உறுதியில்லை',
  rfScore: 'புள்ளிகள்',
  rfStreak: 'தொடர்',
  rfQuit: 'சுற்றை முடி',
  rfTooFast: 'மிக வேகம் — ஒவ்வொன்றையும் படிக்க ஒரு வினாடி எடுங்கள்.',
  rfTimeUp: 'நேரம் முடிந்தது',
  rfSaving: 'சேமிக்கிறது…',
  rfExpired: 'இந்தச் சுற்று காலாவதியானது. புதிய ஒன்றைத் தொடங்குங்கள்.',
  rfSaveError: 'சில பதில்களைச் சேமிக்க முடியவில்லை. இணைப்பைச் சரிபார்க்கவும்.',
  rfResultsTitle: 'சுற்று முடிந்தது!',
  rfResultsBody: 'நீங்கள் {village} க்கு {n} தலைப்புகளைச் சரிபார்த்தீர்கள்.',
  rfBestStreak: 'சிறந்த தொடர்',
  rfAnswered: 'பதிலளித்தவை',
  rfSkipped: 'தவிர்த்தவை',
  rfYesTitle: 'உங்கள் கிராமத்தில் உள்ளன என்று நீங்கள் சொன்னவை',
  rfYesBody: 'மற்றவர்கள் கண்டுபிடிக்க விவரங்களைச் சேர்க்கவும் — உங்கள் கிராமப் பதிவு உண்மையில் வளர்வது இங்குதான்.',
  rfAddDetails: 'விவரங்களைச் சேர்',
  rfPlayAgain: 'மீண்டும் விளையாடு',
  rfOtherDeck: 'வேறு தொகுப்பைத் தேர்ந்தெடு',
  rfBackToContribute: 'பங்களிப்புக்குத் திரும்பு',
  rfRankScout: 'கிராம ஆய்வாளர்',
  rfRankMapper: 'கிராம வரைபடவியலாளர்',
  rfRankExpert: 'கிராம நிபுணர்',
  rfRankLegend: 'கிராம நாயகர்',
  rfPromoTitle: 'ஒரு நிமிடம் உள்ளதா? விரைவுக் கேள்விகளை விளையாடுங்கள்',
  rfPromoBody: 'உங்கள் கிராமத்தைப் பற்றிய விரைவான ஆம்-இல்லை கேள்விகள். விரைவானது, வேடிக்கையானது, ஒவ்வொரு பதிலும் முக்கியம்.',
  rfPromoCta: 'இப்போது விளையாடு',
  statChecked: 'சரிபார்த்தவை',
};

const COPY: Record<'en' | 'si' | 'ta', Copy> = { en, si, ta };

export type ContributeCopy = Copy;

export const fill = (template: string, values: Record<string, string | number>): string =>
  template.replace(/\{(\w+)\}/g, (_, key) => (values[key] !== undefined ? String(values[key]) : `{${key}}`));

export const useContributeCopy = () => {
  const { language } = useLanguage();
  return { t: COPY[language] || en, language };
};

/** Picks the name in the active language, falling back to English. */
export const localName = (
  item: { name_en?: string | null; name_si?: string | null; name_ta?: string | null; nameEn?: string; nameSi?: string; nameTa?: string } | null | undefined,
  language: 'en' | 'si' | 'ta',
): string => {
  if (!item) return '';
  const en = item.name_en ?? item.nameEn ?? '';
  const si = item.name_si ?? item.nameSi ?? '';
  const ta = item.name_ta ?? item.nameTa ?? '';
  if (language === 'si' && si.trim() && si.trim() !== en.trim()) return si;
  if (language === 'ta' && ta.trim() && ta.trim() !== en.trim()) return ta;
  return en || si || ta;
};
