<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class IndustryQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            ['num' => '1.2.1', 'en' => 'Owner\'s full name', 'si' => 'හිමිකරුගේ සම්පූර්ණ නම', 'ta' => 'உரிமையாளரின் முழு பெயர்', 'type' => 'text'],
            ['num' => '1.2.2', 'en' => 'Feminine/Masculinity', 'si' => 'ස්ත්‍රී/පුරුෂ භාවය', 'ta' => 'பெண்/ஆண்மை', 'type' => 'select'],
            ['num' => '1.2.3', 'en' => 'National Identity Card Number', 'si' => 'ජාතික හැඳුනුම්පත් අංකය', 'ta' => 'தேசிய அடையாள அட்டை எண்', 'type' => 'text'],
            ['num' => '1.2.5', 'en' => 'WhatsApp phone number', 'si' => 'වට්ස්ඇප් දුරකථන අංකය', 'ta' => 'வாட்ஸ்அப் தொலைபேசி எண்', 'type' => 'text'],
            ['num' => '1.2.6', 'en' => 'Main phone number', 'si' => 'ප්‍රධාන දුරකථන අංකය', 'ta' => 'முக்கிய தொலைபேசி எண்', 'type' => 'text'],
            ['num' => '1.2.7', 'en' => 'Email address (if any)', 'si' => 'විද්‍යුත් තැපැල් ලිපිනය (ඇත්නම්)', 'ta' => 'மின்னஞ்சல் முகவரி (ஏதேனும் இருந்தால்)', 'type' => 'text'],
            ['num' => '1.2.8', 'en' => 'Residential address', 'si' => 'නිවැසි ලිපිනය', 'ta' => 'குடியிருப்பு முகவரி', 'type' => 'text'],
            ['num' => '1.2.9', 'en' => 'Highest Educational Qualification Date of Birth / Age Select', 'si' => 'උසස්ම අධ්‍යාපන සුදුසුකම උපන් දිනය / වයස Select', 'ta' => 'மிக உயர்ந்த கல்வித் தகுதி பிறந்த தேதி / வயது தேர்வு', 'type' => 'select'],
            ['num' => '1.2.10', 'en' => 'Experience in this Industry (Years)', 'si' => 'මෙම කර්මාන්තයේ පළපුරුද්ද (වසර)', 'ta' => 'இந்தத் துறையில் அனுபவம் (ஆண்டுகள்)', 'type' => 'select'],
            ['num' => '1.2.11', 'en' => 'Employment before starting the industry', 'si' => 'කර්මාන්තය ආරම්භ කිරීමට පෙර රැකියාව', 'ta' => 'தொழில் தொடங்கும் முன் வேலைவாய்ப்பு', 'type' => 'text'],
            ['num' => '1.3.1', 'en' => 'What is the legal form of the business?  Select', 'si' => 'ව්‍යාපාරයේ නීතිමය ස්වරූපය කුමක්ද?  Select', 'ta' => 'வணிகத்தின் சட்ட வடிவம் என்ன?  தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '1.3.2', 'en' => 'Is the business registered? Select', 'si' => 'ව්‍යාපාරය ලියාපදිංචි කර තිබේද? Select', 'ta' => 'வணிகம் பதிவு செய்யப்பட்டதா? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '1.3.3', 'en' => 'If registered, with which agency? (multiple choice) Multiple Choice', 'si' => 'ලියාපදිංචි කර ඇත්නම්, කුමන ආයතනයක් සමඟද? (බහුවරණය) Multiple Choice', 'ta' => 'பதிவு செய்திருந்தால், எந்த நிறுவனத்தில்? (பல தேர்வு) பல தேர்வு', 'type' => 'select'],
            ['num' => '1.3.4', 'en' => 'Registration Number(s) Selected Items', 'si' => 'ලියාපදිංචි අංක(ය) Selected Items', 'ta' => 'பதிவு எண்(கள்) தேர்ந்தெடுக்கப்பட்ட பொருட்கள்', 'type' => 'text'],
            ['num' => '1.3.5', 'en' => '(VAT) Number', 'si' => '(VAT) Number', 'ta' => '(VAT) எண்', 'type' => 'select'],
            ['num' => '2.1.1', 'en' => 'Where does the business operate? Select', 'si' => 'ව්‍යාපාරය ක්‍රියාත්මක වන ස්ථානය කුමක්ද? Select', 'ta' => 'வணிகம் எங்கு செயல்படுகிறது? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '2.1.2', 'en' => 'Address of the place of business Short text', 'si' => 'ව්‍යාපාරික ස්ථානයේ ලිපිනය Short text', 'ta' => 'வணிக இடத்தின் முகவரி குறுகிய உரை', 'type' => 'text'],
            ['num' => '2.1.3', 'en' => 'Branch address(es) (if any) Short text', 'si' => 'ශාඛා ලිපින(ය) (ඇත්නම්) Short text', 'ta' => 'கிளை முகவரி(கள்) (ஏதேனும் இருந்தால்) குறுகிய உரை', 'type' => 'text'],
            ['num' => '2.1.4', 'en' => 'Location Ownership Select', 'si' => 'ස්ථානයේ හිමිකාරිත්වය Select', 'ta' => 'இருப்பிட உரிமை தேர்வு', 'type' => 'select'],
            ['num' => '2.1.5', 'en' => 'If rented, the monthly rental amount', 'si' => 'කුලියට ගෙන ඇත්නම්, මාසික කුලී මුදල', 'ta' => 'வாடகைக்கு இருந்தால், மாத வாடகைத் தொகை', 'type' => 'select'],
            ['num' => '2.1.6', 'en' => 'Paying a tax on the building?', 'si' => 'ගොඩනැගිල්ල සඳහා බද්දක් ගෙවන්නේද?', 'ta' => 'கட்டிடத்திற்கு வரி செலுத்துகிறீர்களா?', 'type' => 'select'],
            ['num' => '2.2.1', 'en' => 'Is electricity used? Select', 'si' => 'විදුලිය භාවිතා කරන්නේද? Select', 'ta' => 'மின்சாரம் பயன்படுத்தப்படுகிறதா? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '2.2.2', 'en' => 'What is the main source of energy? Multiple Select', 'si' => 'ප්‍රධාන බලශක්ති ප්‍රභවය කුමක්ද? Multiple Select', 'ta' => 'ஆற்றலின் முக்கிய ஆதாரம் எது? பல தேர்வு', 'type' => 'select'],
            ['num' => '2.2.3', 'en' => 'How many power outages are there on average per week?', 'si' => 'සතියකට සාමාන්‍යයෙන් විදුලිය ඇනහිටීම් කීයක් සිදුවේද?', 'ta' => 'வாரத்திற்கு சராசரியாக எத்தனை மின்வெட்டு?', 'type' => 'select'],
            ['num' => '2.2.4', 'en' => 'How to get water? Select', 'si' => 'ජලය ලබා ගන්නේ කෙසේද? Select', 'ta' => 'தண்ணீர் பெறுவது எப்படி? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '2.2.5', 'en' => 'Is there a water storage facility? Select', 'si' => 'ජලය ගබඩා කිරීමේ පහසුකමක් තිබේද? Select', 'ta' => 'தண்ணீர் சேமிப்பு வசதி உள்ளதா? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '2.2.6', 'en' => 'Is there internet facility? Select', 'si' => 'අන්තර්ජාල පහසුකම තිබේද? Select', 'ta' => 'இணைய வசதி உள்ளதா? தேர்ந்தெடு', 'type' => 'select'],
            ['num' => '2.2.7', 'en' => 'Is there phone service? Multiple Select', 'si' => 'දුරකථන සේවාව තිබේද? Multiple Select', 'ta' => 'தொலைபேசி சேவை உள்ளதா? பல தேர்வு', 'type' => 'select'],
            ['num' => '3.1.1', 'en' => 'Name of the business', 'si' => 'ව්‍යාපාරයේ නම', 'ta' => 'வணிகத்தின் பெயர்', 'type' => 'text'],
            ['num' => '3.1.2', 'en' => 'Main activity of the business Long text', 'si' => 'ව්‍යාපාරයේ ප්‍රධාන ක්‍රියාකාරකම Long text', 'ta' => 'வணிகத்தின் முக்கிய செயல்பாடு நீண்ட உரை', 'type' => 'text'],
            ['num' => '3.1.3', 'en' => 'Industry by National Classification (ISIC) Select from Dropdown and Universal search', 'si' => 'කර්මාන්තය ජාතික වර්ගීකරණය අනුව (ISIC) Select from Dropdown and Universal search', 'ta' => 'தேசிய வகைப்பாடு (ISIC) மூலம் தொழில்துறை கீழ்தோன்றும் மற்றும் உலகளாவிய தேடலில் இருந்து தேர்ந்தெடுக்கவும்', 'type' => 'text'],
            ['num' => '3.1.4', 'en' => 'Industry subcategory Save as a new category to the database', 'si' => 'කර්මාන්තයේ උප වර්ගීකරණය Save as a new category to the database', 'ta' => 'தொழில்துறை துணைப்பிரிவு தரவுத்தளத்தில் ஒரு புதிய வகையாக சேமி', 'type' => 'text'],
            ['num' => '3.1.5', 'en' => 'Main Products/Services of the Business (Maximum 3) Images (Camera) (Optional)', 'si' => 'ව්‍යාපාරයේ ප්‍රධාන නිෂ්පාදන/සේවා (උපරිම 3) Images (Camera) (Optional)', 'ta' => 'வணிகத்தின் முக்கிய தயாரிப்புகள்/சேவைகள் (அதிகபட்சம் 3) படங்கள் (கேமரா) (விரும்பினால்)', 'type' => 'select'],
            ['num' => '3.1.6', 'en' => 'Date/Year of Inception of Business', 'si' => 'ව්‍යාපාරය ආරම්භ කළ දිනය/වර්ෂය', 'ta' => 'வணிகம் தொடங்கிய தேதி/ஆண்டு', 'type' => 'text'],
            ['num' => '3.1.7', 'en' => 'Initial capital', 'si' => 'ආරම්භක ප්‍රාග්ධනය', 'ta' => 'ஆரம்ப மூலதனம்', 'type' => 'select'],
            ['num' => '3.2.1', 'en' => 'Sources of Initial Capital (Multiple Select)', 'si' => 'ආරම්භක ප්‍රාග්ධනය ලබාගත් මූලාශ්‍ර (Multiple Select)', 'ta' => 'ஆரம்ப மூலதனத்தின் ஆதாரங்கள் (பல்வேறு தேர்வு)', 'type' => 'select'],
            ['num' => '3.3.1', 'en' => 'Scale of Business (Select)', 'si' => 'ව්‍යාපාරයේ පරිමාණය ( Select)', 'ta' => 'வணிகத்தின் அளவு (தேர்ந்தெடுக்கவும்)', 'type' => 'select'],
            ['num' => '3.3.2', 'en' => 'Nature of Business (Select)', 'si' => 'ව්‍යාපාරයේ නියැලීමේ ස්වභාවය ( Select)', 'ta' => 'வணிகத்தின் தன்மை (தேர்ந்தெடுக்கவும்)', 'type' => 'select'],
            ['num' => '3.3.3', 'en' => 'Place of Business (Select)', 'si' => 'ව්‍යාපාරය සිදුකරන ස්ථානය ( Select)', 'ta' => 'வணிக இடம் (தேர்ந்தெடுக்கவும்)', 'type' => 'select'],
            ['num' => '4.1.1', 'en' => 'Total number of people employed in the business (including you)', 'si' => 'ව්‍යාපාරයේ සේවය කරන මුළු පුද්ගලයින් සංඛ්‍යාව (ඔබ ඇතුළුව)', 'ta' => 'வணிகத்தில் பணிபுரியும் நபர்களின் மொத்த எண்ணிக்கை (நீங்கள் உட்பட)', 'type' => 'select'],
            ['num' => '4.1.2', 'en' => 'Out of which the number of women', 'si' => 'ඉන් කාන්තාවන් සංඛ්‍යාව', 'ta' => 'இதில் பெண்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '4.1.3', 'en' => 'Of which the number of males', 'si' => 'ඉන් පිරිමි සංඛ්‍යාව', 'ta' => 'இதில் ஆண்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '4.1.4', 'en' => 'Number of paid employees', 'si' => 'ගෙවන සේවකයින් සංඛ්‍යාව', 'ta' => 'ஊதியம் பெற்ற ஊழியர்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '4.1.5', 'en' => 'Number of unpaid family members', 'si' => 'වැටුප් නොලබන පවුලේ සාමාජිකයින් සංඛ්‍යාව', 'ta' => 'செலுத்தப்படாத குடும்ப உறுப்பினர்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '4.1.6', 'en' => 'Number of casual/contract workers', 'si' => 'වරින් වර/කොන්ත්‍රාත් සේවය කරන අය සංඛ්‍යාව', 'ta' => 'சாதாரண/ஒப்பந்தத் தொழிலாளர்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '4.2.1', 'en' => 'Nature of Labor Contribution (Select)', 'si' => 'ශ්‍රම දායකත්වයේ ස්වභාවය ( Select)', 'ta' => 'தொழிலாளர் பங்களிப்பின் தன்மை (தேர்ந்தெடுக்கவும்)', 'type' => 'select'],
            ['num' => '4.2.2', 'en' => 'Are employees trained? (Select)', 'si' => 'සේවකයින්ට පුහුණුව ලබා දෙනවාද? ( Select)', 'ta' => 'ஊழியர்கள் பயிற்சி பெற்றவர்களா? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '4.2.3', 'en' => 'Are EPF payments made to employees? (Select)', 'si' => 'සේවකයින් සඳහා EPF ගෙවීම් සිදු කරනවාද? ( Select)', 'ta' => 'ஊழியர்களுக்கு EPF செலுத்தப்படுகிறதா? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '5.1.1', 'en' => 'Main Machines Used (Maximum 5) (Camera, Image)', 'si' => 'භාවිතා කරන ප්‍රධාන යන්ත්‍රෝපකරණ (උපරිම 5) ( Camera, Image)', 'ta' => 'பயன்படுத்தப்படும் முக்கிய இயந்திரங்கள் (அதிகபட்சம் 5) (கேமரா, படம்)', 'type' => 'select'],
            ['num' => '5.1.2', 'en' => 'Main Tools Used (Maximum 5) (Camera,Image)', 'si' => 'භාවිතා කරන ප්‍රධාන මෙවලම් (උපරිම 5) ( Camera,Image)', 'ta' => 'பயன்படுத்தப்படும் முக்கிய கருவிகள் (அதிகபட்சம் 5) (கேமரா, படம்)', 'type' => 'select'],
            ['num' => '5.1.3', 'en' => 'Approximate value of machinery', 'si' => 'යන්ත්‍රෝපකරණවල ආසන්න වටිනාකම', 'ta' => 'இயந்திரங்களின் தோராயமான மதிப்பு', 'type' => 'select'],
            ['num' => '5.1.4', 'en' => 'How to get machinery (Multiple Select)', 'si' => 'යන්ත්‍රෝපකරණ ලබාගත් ආකාරය ( Multiple Select)', 'ta' => 'இயந்திரங்களை எவ்வாறு பெறுவது (பல தேர்வு)', 'type' => 'select'],
            ['num' => '5.2.1', 'en' => 'Quantity produced per day', 'si' => 'දිනකට නිෂ්පාදනය කරන ප්‍රමාණය', 'ta' => 'ஒரு நாளைக்கு உற்பத்தி செய்யப்படும் அளவு', 'type' => 'select'],
            ['num' => '5.2.2', 'en' => 'Quantity produced per week', 'si' => 'සතියකට නිෂ්පාදනය කරන ප්‍රමාණය', 'ta' => 'வாரத்திற்கு உற்பத்தி செய்யப்படும் அளவு', 'type' => 'select'],
            ['num' => '5.2.3', 'en' => 'Quantity produced per month', 'si' => 'මාසයකට නිෂ්පාදනය කරන ප්‍රමාණය', 'ta' => 'ஒரு மாதத்திற்கு உற்பத்தி செய்யப்படும் அளவு', 'type' => 'select'],
            ['num' => '5.2.4', 'en' => 'Annual production volume (estimated)', 'si' => 'වාර්ෂික නිෂ්පාදන ප්‍රමාණය (ඇස්තමේන්තුව)', 'ta' => 'ஆண்டு உற்பத்தி அளவு (மதிப்பீடு)', 'type' => 'select'],
            ['num' => '5.2.5', 'en' => 'Utilization percentage of production capacity', 'si' => 'නිෂ්පාදන ධාරිතාවයේ භාවිත ප්‍රතිශතය', 'ta' => 'உற்பத்தி திறனின் பயன்பாட்டு சதவீதம்', 'type' => 'select'],
            ['num' => '5.2.6', 'en' => 'Operating hours per day', 'si' => 'දිනකට මෙහෙයුම් පැය ගණන', 'ta' => 'ஒரு நாளைக்கு செயல்படும் நேரம்', 'type' => 'select'],
            ['num' => '5.3.1', 'en' => 'Main Ingredients Used (Maximum 5) (Camera, Image)', 'si' => 'භාවිතා කරන ප්‍රධාන අමුද්‍රව්‍ය (උපරිම 5) (Camera, Image)', 'ta' => 'பயன்படுத்தப்படும் முக்கிய பொருட்கள் (அதிகபட்சம் 5) (கேமரா, படம்)', 'type' => 'select'],
            ['num' => '5.3.2', 'en' => 'How to procure ingredients (Multiple Select)', 'si' => 'අමුද්‍රව්‍ය සපයා ගන්නා ආකාරය ( Multiple Select)', 'ta' => 'பொருட்கள் வாங்குவது எப்படி (பல தேர்வு)', 'type' => 'select'],
            ['num' => '5.3.3', 'en' => 'Is a license required for ingredients? (Select)', 'si' => 'අමුද්‍රව්‍ය සඳහා බලපත්‍රයක් අවශ්‍යද? ( Select)', 'ta' => 'பொருட்களுக்கு உரிமம் தேவையா? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '5.3.4', 'en' => 'If the license is required from which agency? (Select)', 'si' => 'බලපත්‍රය අවශ්‍ය නම් කුමන ආයතනයෙන්ද? ( Select)', 'ta' => 'எந்த நிறுவனத்திடம் இருந்து உரிமம் தேவை? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '5.3.5', 'en' => 'Monthly cost of raw materials', 'si' => 'අමුද්‍රව්‍ය සඳහා මාසික වියදම', 'ta' => 'மூலப்பொருட்களின் மாதாந்திர செலவு', 'type' => 'select'],
            ['num' => '5.4.1', 'en' => 'How to dispose of waste (Multiple Select)', 'si' => 'අපද්‍රව්‍ය බැහැර කරන ආකාරය ( Multiple Select)', 'ta' => 'கழிவுகளை எவ்வாறு அகற்றுவது (பல தேர்வு)', 'type' => 'select'],
            ['num' => '5.4.2', 'en' => 'Recycling waste? (Select)', 'si' => 'අපද්‍රව්‍ය ප්‍රතිචක්‍රීකරණය කරනවාද? ( Select)', 'ta' => 'கழிவுகளை மறுசுழற்சி செய்வதா? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '5.4.3', 'en' => 'Does waste recycling generate income? (Select)', 'si' => 'අපද්‍රව්‍ය ප්‍රතිචක්‍රීකරණයෙන් ආදායමක් ලැබේද? ( Select)', 'ta' => 'கழிவுகளை மறுசுழற்சி செய்வதால் வருமானம் கிடைக்குமா? (தேர்ந்தெடு)', 'type' => 'select'],
            ['num' => '6.1.1', 'en' => 'Is profit calculated?', 'si' => 'ලාභය ගණනය කර තිබේද?', 'ta' => 'லாபம் கணக்கிடப்படுகிறதா?', 'type' => 'select'],
            ['num' => '6.1.2', 'en' => 'Have unit production costs been calculated?', 'si' => 'ඒකක නිෂ්පාදන පිරිවැය ගණනය කර තිබේද?', 'ta' => 'யூனிட் உற்பத்தி செலவுகள் கணக்கிடப்பட்டதா?', 'type' => 'select'],
            ['num' => '6.1.3', 'en' => 'Monthly Income (approx.)', 'si' => 'මාසික ආදායම (ආසන්න)', 'ta' => 'மாதாந்திர வருமானம் (தோராயமாக)', 'type' => 'select'],
            ['num' => '6.1.4', 'en' => 'Monthly Cost (Approx.)', 'si' => 'මාසික වියදම (ආසන්න)', 'ta' => 'மாதாந்திர செலவு (தோராயமாக)', 'type' => 'select'],
            ['num' => '6.1.5', 'en' => 'Monthly Net Profit (approx.)', 'si' => 'මාසික ශුද්ධ ලාභය (ආසන්න)', 'ta' => 'மாதாந்திர நிகர லாபம் (தோராயமாக)', 'type' => 'select'],
            ['num' => '6.1.6', 'en' => 'Is the business profitable?', 'si' => 'ව්‍යාපාරය ලාභ සහිතව කරගෙන යනවාද?', 'ta' => 'வியாபாரம் லாபகரமானதா?', 'type' => 'select'],
            ['num' => '6.1.7', 'en' => 'Loan repayment installments', 'si' => 'ණය ගෙවීමේ වාරික', 'ta' => 'கடன் திருப்பிச் செலுத்தும் தவணைகள்', 'type' => 'select'],
            ['num' => '6.1.8', 'en' => 'Total amount of debt owed as a business', 'si' => 'ව්‍යාපාරයක් ලෙස ගෙවිය යුතු මුළු ණය ප්‍රමාණය', 'ta' => 'ஒரு வணிகமாக செலுத்த வேண்டிய கடனின் மொத்த அளவு', 'type' => 'select'],
            ['num' => '6.1.9', 'en' => 'Amount owed personally (for business)', 'si' => 'පුද්ගලිකව ණය වී ඇති ප්‍රමාණය (ව්‍යාපාරය සඳහා)', 'ta' => 'தனிப்பட்ட முறையில் செலுத்த வேண்டிய தொகை (வணிகத்திற்காக)', 'type' => 'select'],
            ['num' => '6.2.1', 'en' => 'Is there a bank account for the business?', 'si' => 'ව්‍යාපාරය සඳහා බැංකු ගිණුමක් තිබේද?', 'ta' => 'வணிகத்திற்கு வங்கி கணக்கு உள்ளதா?', 'type' => 'select'],
            ['num' => '6.2.2', 'en' => 'Maintain accounts?', 'si' => 'ගිණුම් පවත්වාගෙන යනවාද?', 'ta' => 'கணக்குகளை பராமரிக்கவா?', 'type' => 'select'],
            ['num' => '6.2.3', 'en' => 'Have a CRIB (Credit Information Bureau) account?', 'si' => 'CRIB (Credit Information Bureau) ගිණුමක් තිබේද?', 'ta' => 'CRIB (கடன் தகவல் பணியகம்) கணக்கு உள்ளதா?', 'type' => 'select'],
            ['num' => '6.2.4', 'en' => 'Ease of getting credit', 'si' => 'ණය ලබා ගැනීමේ පහසුව', 'ta' => 'கடன் பெறுவது எளிது', 'type' => 'select'],
            ['num' => '6.3.1', 'en' => 'How do you make financial decisions in business? (Multiple Select)', 'si' => 'ඔබ ව්‍යාපාරයේ මූල්‍ය තීරණ ගන්නේ කෙසේද? ( Multiple Select)', 'ta' => 'வணிகத்தில் நிதி முடிவுகளை எவ்வாறு எடுப்பது? (பல தேர்வு)', 'type' => 'select'],
            ['num' => '6.3.2', 'en' => 'Considering the interest rate when taking out a business loan?', 'si' => 'ව්‍යාපාර ණය ගැනීමේදී පොලී අනුපාතය ගැන සලකා බලනවාද?', 'ta' => 'தொழில் கடன் வாங்கும்போது வட்டி விகிதத்தைக் கருத்தில் கொள்ளலாமா?', 'type' => 'select'],
            ['num' => '6.3.3', 'en' => 'Read the terms of a loan agreement before signing it?', 'si' => 'ණය ගිවිසුමක් අත්සන් කිරීමට පෙර එහි කොන්දේසි කියවනවාද?', 'ta' => 'கடன் ஒப்பந்தத்தில் கையெழுத்திடும் முன் அதன் விதிமுறைகளைப் படிக்கவா?', 'type' => 'select'],
            ['num' => '7.1.1', 'en' => 'Major Clients (Maximum 3)', 'si' => 'ප්‍රධාන ගනුදෙනුකරුවන් (උපරිම 3)', 'ta' => 'முக்கிய வாடிக்கையாளர்கள் (அதிகபட்சம் 3)', 'type' => 'select'],
            ['num' => '7.1.2', 'en' => 'Market area where goods/services are sold (Multiple Select)', 'si' => 'භාණ්ඩ/සේවා විකුණන වෙළඳපල ප්‍රදේශය (Multiple Select)', 'ta' => 'பொருட்கள்/சேவைகள் விற்கப்படும் சந்தைப் பகுதி (பல்வேறு தேர்வு)', 'type' => 'select'],
            ['num' => '7.1.3', 'en' => 'Exporting?', 'si' => 'අපනයනය කරන්නේද?', 'ta' => 'ஏற்றுமதி செய்கிறதா?', 'type' => 'select'],
            ['num' => '7.2.1', 'en' => 'Number of persons engaged in this industry in the village', 'si' => 'මෙම කර්මාන්තය ගම තුළ කරන පිරිස් සංඛ්‍යාව', 'ta' => 'கிராமத்தில் இந்தத் தொழிலில் ஈடுபட்டுள்ளவர்களின் எண்ணிக்கை', 'type' => 'select'],
            ['num' => '7.2.2', 'en' => 'Number of Major Competitors (within Territory)', 'si' => 'ප්‍රධාන තරඟකරුවන් සංඛ්‍යාව (ප්‍රදේශය තුළ)', 'ta' => 'முக்கிய போட்டியாளர்களின் எண்ணிக்கை (பிரதேசத்திற்குள்)', 'type' => 'select'],
            ['num' => '7.2.3', 'en' => 'Level of competition', 'si' => 'තරඟකාරිත්වයේ මට්ටම', 'ta' => 'போட்டியின் நிலை', 'type' => 'select'],
            ['num' => '7.3.1', 'en' => 'Marketing Methods Used (Multiple Select)', 'si' => 'භාවිතා කරන අලෙවිකරණ ක්‍රම (බහුවරණය) (Multiple Select)', 'ta' => 'பயன்படுத்தப்படும் சந்தைப்படுத்தல் முறைகள் (பல தேர்வு)', 'type' => 'select'],
            ['num' => '7.3.2', 'en' => 'Using social media? (Multiple Select)', 'si' => 'සමාජ මාධ්‍ය භාවිතා කරන්නේද? (Multiple Select)', 'ta' => 'சமூக ஊடகங்களைப் பயன்படுத்துகிறீர்களா? (பல தேர்வு)', 'type' => 'select'],
            ['num' => '7.3.3', 'en' => 'Using online sales platforms? (Multiple Select)', 'si' => 'ඔන්ලයින් විකුණුම් වේදිකා භාවිතා කරන්නේද? (Multiple Select)', 'ta' => 'ஆன்லைன் விற்பனை தளங்களைப் பயன்படுத்துகிறீர்களா? (பல தேர்வு)', 'type' => 'select'],
            ['num' => '7.3.4', 'en' => 'Introduced a new marketing method? (within last 3 years)', 'si' => 'නව අලෙවිකරණ ක්‍රමයක් හඳුන්වා දී තිබේද? (පසුගිය වසර 3 තුළ)', 'ta' => 'புதிய மார்க்கெட்டிங் முறையை அறிமுகப்படுத்தியுள்ளீர்களா? (கடந்த 3 ஆண்டுகளுக்குள்)', 'type' => 'select'],
            ['num' => '8.1.1', 'en' => 'Introduced new or significantly improved products/services in the last 3 years? (After yes keep short text)', 'si' => 'පසුගිය වසර 3 තුළ නව හෝ සැලකිය යුතු ලෙස වැඩිදියුණු කළ නිෂ්පාදන/සේවා හඳුන්වා දුන්නාද? (After yes keep short text)', 'ta' => 'கடந்த 3 ஆண்டுகளில் புதிய அல்லது கணிசமாக மேம்படுத்தப்பட்ட தயாரிப்புகள்/சேவைகள் அறிமுகப்படுத்தப்பட்டதா? (ஆம் என்பதற்குப் பிறகு குறுகிய உரையை வைத்திருங்கள்)', 'type' => 'select'],
            ['num' => '8.1.2', 'en' => 'Have new or significantly improved production methods been introduced in the past 3 years? (After yes keep short text)', 'si' => 'පසුගිය වසර 3 තුළ නව හෝ සැලකිය යුතු ලෙස වැඩිදියුණු කළ නිෂ්පාදන ක්‍රම හඳුන්වා දුන්නාද? (After yes keep short text)', 'ta' => 'கடந்த 3 ஆண்டுகளில் புதிய அல்லது கணிசமாக மேம்படுத்தப்பட்ட உற்பத்தி முறைகள் அறிமுகப்படுத்தப்பட்டதா? (ஆம் என்பதற்குப் பிறகு குறுகிய உரையை வைத்திருங்கள்)', 'type' => 'select'],
            ['num' => '8.1.3', 'en' => 'Conducting research and development (R&D) activities? (After yes keep short text)', 'si' => 'පර්යේෂණ හා සංවර්ධන (R&D) කටයුතු සිදු කරනවාද? (After yes keep short text)', 'ta' => 'ஆராய்ச்சி மற்றும் மேம்பாடு (R&D) நடவடிக்கைகளை நடத்துவது? (ஆம் என்பதற்குப் பிறகு குறுகிய உரையை வைத்திருங்கள்)', 'type' => 'select'],
            ['num' => '8.1.4', 'en' => 'Source of technical advice (Mu;tiple select)', 'si' => 'තාක්ෂණික උපදෙස් ලබා ගන්නා මූලාශ්‍රය (Mu;tiple select)', 'ta' => 'தொழில்நுட்ப ஆலோசனையின் ஆதாரம் (மு;டிபிள் தேர்வு)', 'type' => 'select'],
            ['num' => '8.2.1', 'en' => 'Does the business use ICT?', 'si' => 'ව්‍යාපාරය ICT භාවිතා කරනවාද?', 'ta' => 'வணிகம் ICT பயன்படுத்துகிறதா?', 'type' => 'select'],
            ['num' => '8.2.2', 'en' => 'Using a computer?', 'si' => 'පරිගණකයක් භාවිතා කරනවාද?', 'ta' => 'கணினியைப் பயன்படுத்துகிறீர்களா?', 'type' => 'select'],
            ['num' => '8.2.3', 'en' => 'Using digital payment methods?', 'si' => 'ඩිජිටල් ගෙවීම් ක්‍රම භාවිතා කරනවාද?', 'ta' => 'டிஜிட்டல் கட்டண முறைகளைப் பயன்படுத்துகிறீர்களா?', 'type' => 'select'],
            ['num' => '9.1.1', 'en' => 'Government support/assistance received (Multiple Selection)', 'si' => 'ලැබී ඇති රාජ්‍ය අනුග්‍රහය/සහාය (බහුවරණය) (Multiple Selection)', 'ta' => 'அரசு ஆதரவு/உதவி பெறப்பட்டது (பல தேர்வு)', 'type' => 'select'],
            ['num' => '9.1.2', 'en' => 'Government officials related to the movement (Multiple Selection)', 'si' => 'ව්‍යාපාරය හා සම්බන්ධ රාජ්‍ය නිලධාරින් (Multiple Selection)', 'ta' => 'இயக்கம் தொடர்பான அரசு அதிகாரிகள் (பல்வேறு தேர்வு)', 'type' => 'select'],
            ['num' => '9.1.3', 'en' => 'Think government intervention is enough?', 'si' => 'රජයේ මැදිහත්වීම ප්‍රමාණවත් යැයි සිතනවාද?', 'ta' => 'அரசின் தலையீடு போதுமா?', 'type' => 'select'],
            ['num' => '9.1.4', 'en' => 'How the government should intervene', 'si' => 'රජය මැදිහත් විය යුතු ආකාරය', 'ta' => 'அரசு எப்படி தலையிட வேண்டும்', 'type' => 'text'],
            ['num' => '9.2.1', 'en' => 'Current Major Problems (Multiple Selection)', 'si' => 'දැනට පවතින ප්‍රධාන ගැටළු (බහුවරණය) (Multiple Selection)', 'ta' => 'தற்போதைய முக்கிய பிரச்சனைகள் (பல தேர்வு)', 'type' => 'select'],
            ['num' => '9.2.2', 'en' => 'The owner\'s assessment of the state of the business', 'si' => 'ව්‍යාපාරයේ තත්ත්වය පිළිබඳ හිමිකරුගේ ඇගයීම', 'ta' => 'வணிகத்தின் நிலையை உரிமையாளரின் மதிப்பீடு', 'type' => 'select'],
            ['num' => '9.2.3', 'en' => 'Cause to be moderate or weak', 'si' => 'මධ්‍යස්ථ හෝ දුර්වල වීමට හේතුව', 'ta' => 'மிதமான அல்லது பலவீனமாக இருக்க காரணம்', 'type' => 'text'],
            ['num' => '9.2.4', 'en' => 'Current problems of the business (details)', 'si' => 'ව්‍යාපාරයේ දැනට පවතින ගැටළු (විස්තර)', 'ta' => 'வணிகத்தின் தற்போதைய சிக்கல்கள் (விவரங்கள்)', 'type' => 'text'],
            ['num' => '9.2.5', 'en' => 'Problems in Expanding the Business (Multiple Selection)', 'si' => 'ව්‍යාපාරය පුළුල් කිරීමට ඇති ගැටළු (බහුවරණය) (Multiple Selection)', 'ta' => 'வணிகத்தை விரிவுபடுத்துவதில் உள்ள சிக்கல்கள் (பல்வேறு தேர்வு)', 'type' => 'select'],
            ['num' => '9.3.1', 'en' => 'Electricity supply', 'si' => 'විදුලිය සැපයුම', 'ta' => 'மின்சார விநியோகம்', 'type' => 'select'],
            ['num' => '9.3.2', 'en' => 'Transportation', 'si' => 'ප්‍රවාහනය', 'ta' => 'போக்குவரத்து', 'type' => 'select'],
            ['num' => '9.3.3', 'en' => 'Access to financial services', 'si' => 'මූල්‍ය සේවා සඳහා ප්‍රවේශය', 'ta' => 'நிதி சேவைகளுக்கான அணுகல்', 'type' => 'select'],
            ['num' => '9.3.4', 'en' => 'Acquisition of land', 'si' => 'ඉඩම් ලබාගැනීම', 'ta' => 'நிலம் கையகப்படுத்துதல்', 'type' => 'select'],
            ['num' => '9.3.5', 'en' => 'Tax payments', 'si' => 'බදු ගෙවීම්', 'ta' => 'வரி செலுத்துதல்', 'type' => 'select'],
            ['num' => '9.3.6', 'en' => 'Regulatory compliance', 'si' => 'නියාමන අනුකූලතාව', 'ta' => 'ஒழுங்குமுறை இணக்கம்', 'type' => 'select'],
            ['num' => '9.3.7', 'en' => 'Finding skilled workers', 'si' => 'දක්ෂ ශ්‍රමිකයින් සොයාගැනීම', 'ta' => 'திறமையான தொழிலாளர்களைக் கண்டறிதல்', 'type' => 'select'],
            ['num' => '9.3.8', 'en' => 'Competition', 'si' => 'තරඟකාරිත්වය', 'ta' => 'போட்டி', 'type' => 'select'],
            ['num' => '9.3.9', 'en' => 'Crime/Theft', 'si' => 'අපරාධ/සොරකම්', 'ta' => 'குற்றம்/திருட்டு', 'type' => 'select'],
            ['num' => '10.1.1', 'en' => 'Environmental impact of business', 'si' => 'ව්‍යාපාරයේ පාරිසරික බලපෑම', 'ta' => 'வணிகத்தின் சுற்றுச்சூழல் தாக்கம்', 'type' => 'select'],
            ['num' => '10.1.2', 'en' => 'Nature of Effect (Multiple Selection)', 'si' => 'බලපෑමේ ස්වභාවය (බහුවරණය) (Multiple Selection)', 'ta' => 'விளைவின் தன்மை (பல தேர்வு)', 'type' => 'select'],
            ['num' => '10.1.3', 'en' => 'Taking action to reduce environmental impact?', 'si' => 'පාරිසරික බලපෑම අවම කිරීමට ක්‍රියාමාර්ග ගන්නවාද?', 'ta' => 'சுற்றுச்சூழல் பாதிப்பை குறைக்க நடவடிக்கை எடுப்பதா?', 'type' => 'select'],
            ['num' => '10.1.4', 'en' => 'Provide eco-friendly products/services?', 'si' => 'පරිසර හිතකාමී නිෂ්පාදන/සේවා සපයනවාද?', 'ta' => 'சூழல் நட்பு பொருட்கள்/சேவைகளை வழங்கவா?', 'type' => 'select'],
            ['num' => '10.2.1', 'en' => 'Neighbors attitude', 'si' => 'අසල්වැසියන්ගේ ආකල්පය', 'ta' => 'அண்டை நாடுகளின் அணுகுமுறை', 'type' => 'select'],
            ['num' => '10.2.2', 'en' => 'Owner\'s opinion about expanding this industry to others in the village', 'si' => 'මෙම කර්මාන්තය ගම තුළ තවත් අයට ව්‍යාප්ත කිරීම ගැන හිමිකරුගේ මතය', 'ta' => 'கிராமத்தில் உள்ள மற்றவர்களுக்கு இந்தத் தொழிலை விரிவுபடுத்துவது பற்றி உரிமையாளரின் கருத்து', 'type' => 'select'],
            ['num' => '10.2.3', 'en' => 'Contribution of the business to the community', 'si' => 'ව්‍යාපාරය ප්‍රජාවට ලබා දෙන දායකත්වය', 'ta' => 'சமூகத்திற்கு வணிகத்தின் பங்களிப்பு', 'type' => 'text'],
            ['num' => '10.2.4', 'en' => 'Are there conflicts/conflicts in the community?', 'si' => 'ප්‍රජාව තුළ ගැටුම්/ආරවුල් තිබේද?', 'ta' => 'சமூகத்தில் மோதல்கள்/மோதல்கள் உள்ளதா?', 'type' => 'select'],
            ['num' => '11.1.1', 'en' => 'Help from family', 'si' => 'පවුලෙන් ලැබෙන උදව්', 'ta' => 'குடும்பத்தில் இருந்து உதவி', 'type' => 'text'],
            ['num' => '11.1.2', 'en' => 'Obstacles from family', 'si' => 'පවුලෙන් ඇති වන බාධා', 'ta' => 'குடும்பத்தில் இருந்து தடைகள்', 'type' => 'text'],
            ['num' => '11.1.3', 'en' => 'Do other family members have similar businesses?', 'si' => 'පවුලේ වෙනත් සාමාජිකයින්ට ද මෙවැනි ව්‍යාපාර තිබේද?', 'ta' => 'மற்ற குடும்ப உறுப்பினர்களுக்கும் இதே போன்ற தொழில்கள் உள்ளதா?', 'type' => 'select'],
            ['num' => '11.2.1', 'en' => 'Societies/Groups/Organizations (Multiple Selection) that you are associated with in the village related to the business.', 'si' => 'ඔබ ව්‍යාපාරයට අදාළව ගමේ සම්බන්ධ වී ඇති සමිති/කණ්ඩායම්/සංවිධාන (බහුවරණය) (Multiple Selection)', 'ta' => 'வணிகம் தொடர்பான கிராமத்தில் நீங்கள் தொடர்புடைய சங்கங்கள்/குழுக்கள்/நிறுவனங்கள் (பல தேர்வு).', 'type' => 'select'],
            ['num' => '11.2.2', 'en' => 'Collaborating with other business owners?', 'si' => 'වෙනත් ව්‍යාපාර හිමියන් සමඟ සහයෝගයෙන් කටයුතු කරනවාද?', 'ta' => 'மற்ற வணிக உரிமையாளர்களுடன் ஒத்துழைக்கிறீர்களா?', 'type' => 'select'],
            ['num' => '11.2.3', 'en' => 'Member of a business association/trade chamber?', 'si' => 'ව්‍යාපාරික සංගමයක/වෙළඳ සභාවක සාමාජිකයෙක්ද?', 'ta' => 'வணிக சங்கம்/வர்த்தக அறையின் உறுப்பினரா?', 'type' => 'select'],
            ['num' => '12.1.1', 'en' => 'Current Requirements (Multiple Selection)', 'si' => 'දැනට අවශ්‍ය දේවල් (බහුවරණය) (Multiple Selection)', 'ta' => 'தற்போதைய தேவைகள் (பல தேர்வு)', 'type' => 'select'],
            ['num' => '12.1.2', 'en' => 'Got land to move to a new location?', 'si' => 'නව ස්ථානයකට යාමට ඉඩමක් තිබේද?', 'ta' => 'புதிய இடத்திற்கு மாற்ற நிலம் உள்ளதா?', 'type' => 'select'],
            ['num' => '12.1.3', 'en' => 'Need land or a place?', 'si' => 'ඉඩමක් හෝ ස්ථානයක් අවශ්‍යද?', 'ta' => 'நிலம் அல்லது இடம் வேண்டுமா?', 'type' => 'select'],
            ['num' => '12.1.4', 'en' => 'Types of advice/assistance received (Multiple Selection) Keep a DESCRIPTION', 'si' => 'ලැබුණු උපදේශන/සහාය වර්ග (බහුවරණය) (Multiple Selection) Keep a DESCRIPTION', 'ta' => 'பெறப்பட்ட ஆலோசனைகள்/உதவி வகைகள் (பல்வேறு தேர்வு) ஒரு விளக்கத்தை வைத்திருங்கள்', 'type' => 'select'],
            ['num' => '12.2.1', 'en' => 'Planning to expand the business in the next 1 year?', 'si' => 'ඉදිරි වසර 1 තුළ ව්‍යාපාරය පුළුල් කිරීමට සැලසුම් කරනවාද?', 'ta' => 'அடுத்த 1 வருடத்தில் தொழிலை விரிவுபடுத்த திட்டமிட்டுள்ளீர்களா?', 'type' => 'select'],
            ['num' => '12.2.2', 'en' => 'Capital required for expansion', 'si' => 'පුළුල් කිරීමට අවශ්‍ය ප්‍රාග්ධනය', 'ta' => 'விரிவாக்கத்திற்கு தேவையான மூலதனம்', 'type' => 'select'],
            ['num' => '12.2.3', 'en' => 'Planning to hire new employees?', 'si' => 'නව සේවකයින් බඳවා ගැනීමට සැලසුම් කරනවාද?', 'ta' => 'புதிய பணியாளர்களை பணியமர்த்த திட்டமிட்டுள்ளீர்களா?', 'type' => 'select'],
            ['num' => '12.2.4', 'en' => 'Planning to introduce new products/services?', 'si' => 'නව නිෂ්පාදන/සේවා හඳුන්වා දීමට සැලසුම් කරනවාද?', 'ta' => 'புதிய தயாரிப்புகள்/சேவைகளை அறிமுகப்படுத்த திட்டமிட்டுள்ளீர்களா?', 'type' => 'select'],
            ['num' => '13.1.1', 'en' => 'Government programs involving business (Multiple Selection)', 'si' => 'ව්‍යාපාරය සම්බන්ධ වන රාජ්‍ය වැඩසටහන් (බහුවරණය) (Multiple Selection)', 'ta' => 'வணிகம் சம்பந்தப்பட்ட அரசு திட்டங்கள் (பல தேர்வு)', 'type' => 'select'],
            ['num' => '13.1.2', 'en' => 'Benefits received from these programs', 'si' => 'මෙම වැඩසටහන් වලින් ලැබුණු ප්‍රතිලාභ', 'ta' => 'இந்த திட்டங்களில் இருந்து கிடைக்கும் நன்மைகள்', 'type' => 'text'],
            ['num' => '13.1.3', 'en' => 'Ease of applying for programs', 'si' => 'වැඩසටහන් සඳහා අයදුම් කිරීමේ පහසුව', 'ta' => 'திட்டங்களுக்கு விண்ணப்பிப்பது எளிது', 'type' => 'select'],
            ['num' => '13.2.1', 'en' => 'Has the business been evaluated? (Multiple Selection)', 'si' => 'ව්‍යාපාරය ඇගයීමකට ලක්වී තිබේද? (Multiple Selection)', 'ta' => 'வணிகம் மதிப்பிடப்பட்டதா? (பல தேர்வு)', 'type' => 'select'],
            ['num' => '13.2.2', 'en' => 'Received awards/recognitions?', 'si' => 'සම්මාන/පිළිගැනීම් ලැබී තිබේද?', 'ta' => 'விருதுகள்/அங்கீகாரங்கள் கிடைத்ததா?', 'type' => 'select'],
            ['num' => '14.1.1', 'en' => 'Vehicle Used for Business (Multiple Selection)', 'si' => 'ව්‍යාපාරය සඳහා භාවිතා කරන වාහනය (Multiple Selection)', 'ta' => 'வணிகத்திற்காக பயன்படுத்தப்படும் வாகனம் (பல்வேறு தேர்வு)', 'type' => 'select'],
            ['num' => '14.1.2', 'en' => 'How raw materials are transported', 'si' => 'අමුද්‍රව්‍ය ප්‍රවාහනය කරන ආකාරය', 'ta' => 'மூலப்பொருட்கள் எவ்வாறு கொண்டு செல்லப்படுகின்றன', 'type' => 'text'],
            ['num' => '14.1.3', 'en' => 'How to transport manufactured goods', 'si' => 'නිෂ්පාදිත භාණ්ඩ ප්‍රවාහනය කරන ආකාරය', 'ta' => 'தயாரிக்கப்பட்ட பொருட்களை எவ்வாறு கொண்டு செல்வது', 'type' => 'text'],
            ['num' => '14.1.4', 'en' => 'Monthly transportation cost', 'si' => 'මාසික ප්‍රවාහන වියදම', 'ta' => 'மாதாந்திர போக்குவரத்து செலவு', 'type' => 'select'],
            ['num' => '15.1', 'en' => 'How to expand further in the village', 'si' => 'ගම තුළ තවදුරටත් ව්‍යාප්ත කළ හැකි ආකාරය', 'ta' => 'கிராமத்தில் மேலும் விரிவாக்கம் செய்வது எப்படி', 'type' => 'select'],
            ['num' => '15.2', 'en' => 'Other comments/suggestions', 'si' => 'වෙනත් අදහස්/යෝජනා', 'ta' => 'பிற கருத்துகள்/பரிந்துரைகள்', 'type' => 'text'],
        ];

        // Delete old before seeding
        Question::where('section', 'INDUSTRY_SURVEY')->delete();

        $sortOrder = 10;
        foreach ($questions as $q) {
            $prefix = $q['num'] . ' ';
            Question::create([
                "section" => "INDUSTRY_SURVEY",
                "question_text_en" => $prefix . $q["en"],
                "question_text_si" => $prefix . $q["si"],
                "question_text_ta" => $prefix . $q["ta"],
                "input_type" => $q['type'],
                "is_repeater" => false,
                "sort_order" => $sortOrder,
                "is_active" => true,
                "is_standard" => true,
            ]);
            $sortOrder += 10;
        }
    }
}
